#!/usr/bin/env python3
"""Derive the IRON STORM "CUT A" demo pair from the user's authoritative STP export.

WHY THIS IS A SCRIPT AND NOT A HAND EDIT
    The export is regenerated by STP whenever the plan changes. Every change this cut
    needs is mechanical, so it is expressed here once and re-applied on demand: re-run
    the script after a re-export and the derived pair is rebuilt, or the script FAILS
    LOUDLY because an assumption it depends on (a uuid, a task, an element order) no
    longer holds. It never edits in place and never guesses.

INPUTS  (byte-exact, never modified)
    data/STP-IRON-STORM-SYNTHETIC_Initialization.xml
    data/STP-IRON-STORM-SYNTHETIC_Order.xml
OUTPUTS (tracked)
    data/IRONSTORM_CUTA_Initialization.xml
    data/IRONSTORM_CUTA_Order.xml
    data/IRONSTORM_CUTA_E1_Order.xml     the REGISTERED VARIANT "--without i" (run E1): the
                                         same derivation with change (i) left out - see
                                         VARIANTS at the end of the change list
    data/IRONSTORM_FULL_Order.xml        the FULL VARIANT "--variant full": every task but T12,
                                         the same changes - see THE FULL VARIANT below

THE COMPLETE CHANGE LIST - nothing else is touched. Exactly ONE coordinate pair moves
(change (e), a user ruling); no unit is renamed, exactly THREE TaskActionCodes are altered
and ONE AffectedEntity added (changes (f) and (g), owner directions), exactly THREE graphics are
added (change (h), an owner selection: T10's reroute; change (i), T14's lake-edge waypoint;
change (j), T10's second waypoint off a pond),
none is removed, no comment is rewritten, and the root element + namespace + CRLF line endings are
preserved byte for byte. See data/IRONSTORM_CUTA_CHANGES.md for the rationale
and the consequences.

  (a) DURATION FORMAT (connector bug STP-848). Every IsoTimeDuration value is rewritten
      from the canonical-ISO short form the export writes ("PT20M") to the C2SIM 1.1
      pattern form ("P00Y00M00DT00H20M00S"). The schema's IsoTimeDurationBaseType is an
      xs:string restricted by
        [P]{1}[0-9]{2}[Y]{1}[0-9]{2}[M]{1}[0-9]{2}[D]{1}T{1}[0-9]{2}[H]{1}[0-9]{2}[M]{1}[0-9]{2}[S]{1}
      (C2SIM_SMX_LOX_CWIX2024.xsd:17-24) - every field present, two digits wide. The
      short form is NOT valid C2SIM 1.1, and OrderParser.FindTotalIsoMs refuses it
      (returns -1 -> DurationMs 0), which is what leaves the export's HoldInPlace tasks
      MALFORMED and their STREND successors waiting out the gate. This rewrite changes
      no VALUE - only the spelling. 46 values in the order; the init carries none.

  (b) TWO MapGraphicID REFERENCES ADDED, to existing graphics the order ALREADY carries.
      No new geometry is authored.
        T02 (28ID, ATTACK)     -> c8cde9b6-17f7-f253-800e-4de0cae84db3
                                  PassagePoint_28ID_SLOT0
        T10 (1-112 IN, CRESRV) -> cc23071f-aa60-9f52-884c-11505051cc99
                                  PassagePoint_48_IBCT_SLOT0
      Both tasks carry NO geometry at all in the export, so both execute in place and
      the cut has nothing to watch. MapGraphicID is inserted immediately before Name,
      which is where the schema's ActionGroup sequence puts it.

  (c) THE ORDER IS REDUCED to the CUT-3 task set plus the predecessors its temporal
      chains need. KEPT: T01 -> T02 (28ID), T10 (1-112 IN, a chain root), T13 -> T14
      (48 IBCT). DROPPED: the other 18 tasks. Chain integrity is ASSERTED, not assumed:
      every kept task's ActionTemporalRelationship/TemporalAssociationWithAction must
      name a task that is also kept, or the script fails.

  (d) SystemName IS LEFT AS EXPORTED ("Not Set" - connector bug STP-847). The run passes
      --client-id "Not Set" so that the interface's own ClientId filter matches. This is
      deliberately NOT papered over in the data: the defect belongs on the producer side
      and the data file is the evidence.

  (e) T14's DESTINATION IS MOVED 799 m DUE WEST, out of a lake - the ONE coordinate this
      script changes. USER RULING 2026-09-21 ("as recommended"); STP will not re-author it.
        BEFORE  54.04034819271516 / 23.336444730300467
        AFTER   54.040348        / 23.324206
      The authored leg crosses CLCplus class 100 (preset="Water") for 1,565 m of its
      2,757 m, and deep-water is acceleration-factor 0.000000, so the unit would stop dead
      with the task reported TaskRunning for ever. Applied to the graphic the interface
      actually drives AND to T14's mirrored embedded Location - see apply_water_nudge.
      NO OTHER COORDINATE MOVES.

  (f) T14's TaskActionCode ATTACK -> FOLSPT, plus a second AffectedEntity = 116 ABCT.
      OWNER DIRECTION 2026-09-26 ("hack the xml you are using to have the correct codes
      while stp itself is patched"). STP defect (STP-846 family): the STP source
      STP-IRON-STORM-SYNTHETIC_Narrative1.op gives T14 what: 'FOLLOW_AND_SUPPORT' and
      supported: 116 ABCT (884518d7); the connector's C2SimTask.MWTaskCode switches on
      What.ToLower() = "follow_and_support" but its case label is "follow and support"
      (STP HEAD BridgingAgents/C2SimBridge/C2SimBridge/C2SimTask.cs:297-299), so it falls
      through to "return TaskActionCodeType.ATTACK" (:670). FOLSPT is in the C2SIM order
      schema's TaskActionCodeType (C2SIM_SMX_LOX_ASX_v1.0.1_Order_flat.xsd:1854) and in the
      SDK enum. The supported unit goes in as a SECOND AffectedEntity (AffectedEntity is
      maxOccurs unbounded, xsd:2759) after the exported self-reference, which stays first;
      116 ABCT is asserted present in the init. No TaskFunctionalRelation is added. The
      interface reads only the FIRST AffectedEntity (OrderParser.cs FirstOrEmpty), so the
      second one is carried for data fidelity only. NOT PATCHED, on purpose: T02 (what
      'RECEIVE' - STP has no mapping, `//case "RECEIVE,` is commented out at :545, and the
      schema has no receive code, so there is no agreed code to restore; it stays ATTACK).

  (g) T01's and T13's TaskActionCode ExecutePlanPhase -> CNFPSL. OWNER DECISION 2026-09-26
      ("Patch + Jira"). STP defect, same class as (f): both STP source tasks
      ('ConductFwdPassageOfLines', 28ID and 48 IBCT) have what 'NOT_SPECIFIED' and how
      'PASSAGE_OF_LINES'; the connector then switches on How.ToLower() (STP HEAD
      C2SimTask.cs:609) but the case label is the UPPER-case "PASSAGE_OF_LINES" (:645-646,
      which returns CNFPSL), so it never matches and falls to "return
      TaskActionCodeType.ExecutePlanPhase" (:668). CNFPSL is in the C2SIM order schema's
      TaskActionCodeType (C2SIM_SMX_LOX_ASX_v1.0.1_Order_flat.xsd:1789) and in the SDK
      enum. Only the code changes - no AffectedEntity, Duration or relation is touched.
      CONSEQUENCE: until the interface maps a CNFPSL verb, T01 and T13 are unmapped verbs,
      and the T01->T02 / T13->T14 STREND chains depend on how the interface treats them.

  (h) T10 IS REROUTED round nav-area sectors (28,21) and (28,22). OWNER SELECTION 2026-09-26
      ("Maples + reroute T10's leg around the two sectors (Recommended)"). ONE waypoint,
      54.029734 / 23.305499, carried by ONE added Line/Route graphic (c8d9cd1a...; vertices =
      1-112 IN's init position, asserted, then the waypoint) referenced by T10 before its (b)
      PassagePoint. The interface's route assembly drops the start vertex (within 100 m of the
      taskee) and appends the PassagePoint as the destination: start -> waypoint -> PassagePoint,
      2,729 m. Every route sector reads >= 0.9 on the red-maple nav area and both legs are dry
      (CHANGES.md (h)). See apply_reroute.

  (i) T14 IS ROUTED ROUND THE LAKE Jezioro Wiersnie (OSM way 197345448). 2026-09-27, lane T14.
      In the 2026-09-27 pre-warm 48 IBCT drove 850 m of its (e)-nudged leg and stopped dead
      0.5 m outside that OSM water polygon (natural=water -> coverage value 80 -> preset Water
      -> BM_WATER -> deeplake -> deep-water, acceleration-factor 0.0). (e) was checked dry on
      CLCplus ONLY; the nudged centreline enters the OSM polygon at 834 m. ONE waypoint,
      54.014600 / 23.331500 (south-east of the lake), carried by ONE added Line/Route graphic
      (7ff48b93...; vertices = 48 IBCT's init position, asserted, then the waypoint) referenced by
      T14 BEFORE its FollowAndSupport graphic, whose destination is unchanged:
      start -> waypoint -> 54.040348 / 23.324206, 4,169 m (was 2,426 m). >= 60 m from water of
      any source on both legs; maple-area corridor PASS (CHANGES.md (i)). See apply_t14_waypoint.

  (j) T10's (h) LEG 2 IS KEPT OFF AN OSM POND. 2026-09-27, lane T10. (h)'s second leg runs down the
      east edge of an OSM natural=water pond (deep-water, the (i) chain): 1 centreline sample at
      54.02359 / 23.31049 and 81 / 102 samples at 25 / 50 m right of travel - and 1-112 IN moves
      as a 6-7 member formation. ONE more waypoint, 54.024000 / 23.313000 (east of the pond),
      carried by ONE added Line/Route graphic (51a59f89...; vertices = 1-112 IN's init position,
      asserted, then the waypoint) referenced by T10 after (h) and before the (b) PassagePoint:
      start -> 54.029734 / 23.305499 -> 54.024000 / 23.313000 -> PassagePoint (UNCHANGED),
      2,775 m (was 2,729 m). >= 110 m from water of any source on all three legs, >= 164 m from
      sectors (28,21)/(28,22); maple-area corridor PASS (CHANGES.md (j)). See apply_t10_waypoint.

  VARIANTS - a change LEFT OUT, only where a registered run needs it (VARIANTS below).
    "--without i" (2026-09-27, run E1; docs/PLAN_MOVEMENT_2026-09-27.md row E1, ruling
      RL-20260927-01) -> data/IRONSTORM_CUTA_E1_Order.xml. The same derivation with change (i)
      left out: T14 keeps its ORIGINAL line - the FollowAndSupport graphic 7351f662 only - to the
      (e) destination, which STAYS. (a)-(h) and (j) are applied exactly as above; the init is the
      same byte-identical copy. Purpose: a lone platform is now driven by Move To per vertex, so
      the vendor's PLANNER, not a hand waypoint, has to take T14 round the lake. The original line
      is ASSERTED (assert_t14_original_line), not assumed. Only 'i' may be left out; every other
      letter is refused - (k), on an unmerged branch, is not a change of this derivation at all.
    Every run of the script derives EVERY variant, gates each, and proves the without-(i) order is
    the full order minus exactly (i)'s two insertions (remove_change_i) - one change apart, so a
    run on it varies T14's route and nothing else. `--check` verifies every variant on disk.

  THE FULL VARIANT - "--variant full" (2026-10-04, lane FD; RL-20261004-04, demo first)
      -> data/IRONSTORM_FULL_Order.xml. The WHOLE narrative instead of the cut: (c) is replaced by
      "keep ALL 23 tasks EXCEPT T12" (116 ABCT DESTRY, 52.6 km to Alytus over terrain tiles that
      are not cached - tier 2; nothing depends on it). Every other change applies unchanged where
      its task exists: (a) on all 44 remaining IsoTimeDuration values, (b), (e), (f), (h), (i), (j)
      exactly as for cut A, and (g) on T01, T13 AND T03 - T03's STP source is the third
      'ConductFwdPassageOfLines' task (56 SBCT; how 'PASSAGE_OF_LINES', what 'NOT_SPECIFIED'), the
      same connector case-mismatch (g) documents, so (g)'s reasoning covers it. The init needs no
      change: no init file is written for it; the run uses the export's init (byte-identical to
      data/IRONSTORM_CUTA_Initialization.xml). The inserted lines keep their "ADDED BY CUT A"
      comments so every cut-A task block is BYTE-IDENTICAL in the full order - asserted on every
      run (assert_full_extends_cuta), with the non-task remainder of the two orders identical too.
      Change list and the per-task prediction: data/IRONSTORM_FULL_CHANGES.md.

USAGE
    python tools/scenario/derive_ironstorm_cuta.py                 # write the pair
    python tools/scenario/derive_ironstorm_cuta.py --without i     # write the E1 variant
    python tools/scenario/derive_ironstorm_cuta.py --variant full  # write the FULL order
    python tools/scenario/derive_ironstorm_cuta.py --check         # verify ALL, write nothing
    python tools/scenario/derive_ironstorm_cuta.py --selftest      # pure-function tests
EXIT: 0 ok; 2 a gate failed; 3 --check found a mismatch; 4 a --without letter (or --without with
--variant full) was refused.

The script is deterministic: the same inputs always produce byte-identical outputs, and
it prints the SHA-256 of every input and output so a derivation can be audited later.
"""

import argparse
import hashlib
import math
import os
import re
import sys
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

SRC_INIT = os.path.join(REPO, 'data', 'STP-IRON-STORM-SYNTHETIC_Initialization.xml')
SRC_ORDER = os.path.join(REPO, 'data', 'STP-IRON-STORM-SYNTHETIC_Order.xml')
OUT_INIT = os.path.join(REPO, 'data', 'IRONSTORM_CUTA_Initialization.xml')
OUT_ORDER = os.path.join(REPO, 'data', 'IRONSTORM_CUTA_Order.xml')
OUT_ORDER_E1 = os.path.join(REPO, 'data', 'IRONSTORM_CUTA_E1_Order.xml')
OUT_ORDER_FULL = os.path.join(REPO, 'data', 'IRONSTORM_FULL_Order.xml')

NS = 'http://www.sisostds.org/schemas/C2SIM/1.1'
Q = '{%s}' % NS

# ---------------------------------------------------------------------------
# (c) THE CUT. uuid -> the label this project uses for the task in its records.
# The order is the order the tasks appear in the export, which is the order they are
# written out in; nothing is resequenced.
# ---------------------------------------------------------------------------
KEEP = {
    'f7b52ba4-c889-4a28-9f3a-e9715cd8a65f': 'T01',  # 28ID     ExecutePlanPhase->CNFPSL (g) (root)
    '696fbb33-3dce-4854-8935-55fed398c247': 'T02',  # 28ID     ATTACK, STREND on T01
    '9aab7fe6-c7fb-4e74-b586-e11a00fc3eb9': 'T10',  # 1-112 IN CRESRV (root)
    '37677c40-c595-4b4c-9039-e9865abb4eb3': 'T13',  # 48 IBCT  ExecutePlanPhase->CNFPSL (g) (root)
    '1075b583-a7b8-45e5-b22b-d09988c9443e': 'T14',  # 48 IBCT  ATTACK->FOLSPT (f), STREND on T13
}

# ---------------------------------------------------------------------------
# (b) THE TWO ADDED REFERENCES. task uuid -> (graphic uuid, the graphic's Name in the
# export). The Name is carried here so the script can VERIFY it rather than trust it.
# ---------------------------------------------------------------------------
ADD_GRAPHIC = {
    '696fbb33-3dce-4854-8935-55fed398c247': (
        'c8cde9b6-17f7-f253-800e-4de0cae84db3',
        'PassagePoint_28ID_SLOT0__FRIENDLY_PASSAGE_POINT_PassagePoint_28',
        'PassagePoint_28ID_SLOT0'),
    '9aab7fe6-c7fb-4e74-b586-e11a00fc3eb9': (
        'cc23071f-aa60-9f52-884c-11505051cc99',
        'PassagePoint_48_IBCT_SLOT0__FRIENDLY_PASSAGE_POINT_PassagePoint',
        'PassagePoint_48_IBCT_SLOT0'),
}

EOL = '\r\n'
INDENT = ' ' * 10          # the export's indent for ManeuverWarfareTask children

# ---------------------------------------------------------------------------
# (f) and (g) THE CODE REPAIRS (owner directions 2026-09-26; see the docstring). task
# uuid -> (change letter, exported code, restored code, supported unit uuid or None, its
# comment label or None, the STP C2SimTask.cs lines of the defect).
# ---------------------------------------------------------------------------
CODE_FIX = {
    'f7b52ba4-c889-4a28-9f3a-e9715cd8a65f': (
        'g', 'ExecutePlanPhase', 'CNFPSL', None, None, ':609/:645-646/:668'),
    '37677c40-c595-4b4c-9039-e9865abb4eb3': (
        'g', 'ExecutePlanPhase', 'CNFPSL', None, None, ':609/:645-646/:668'),
    '1075b583-a7b8-45e5-b22b-d09988c9443e': (
        'f', 'ATTACK', 'FOLSPT', '884518d7-5b82-a455-98de-64aae833d633', '116_ABCT/28ID',
        ':131/:297-299/:670'),
}

# ---------------------------------------------------------------------------
# THE FULL VARIANT (2026-10-04, lane FD; RL-20261004-04 "demo first"). The export's 23 tasks,
# in export order, with the label this project uses for each. The full variant ASSERTS the
# export still carries exactly these, in this order, before it derives anything.
# ---------------------------------------------------------------------------
EXPORT_TASKS = (
    ('f7b52ba4-c889-4a28-9f3a-e9715cd8a65f', 'T01'),  # 28ID     ExecutePlanPhase -> CNFPSL (g)
    ('696fbb33-3dce-4854-8935-55fed398c247', 'T02'),  # 28ID     ATTACK (STP-846), + (b)
    ('4edbc258-07f9-4be4-991c-b3093b11e142', 'T03'),  # 56 SBCT  ExecutePlanPhase -> CNFPSL (g, FULL)
    ('0c0bb2cf-eab8-45ce-87e0-23a7a68444dc', 'T04'),  # 56 SBCT  FIX
    ('f8b65950-5b7b-436e-a968-56da92ffbf5c', 'T05'),  # 56 SBCT  RETAIN
    ('a4ffa19d-8775-4d5b-a767-7576d5b24b22', 'T06'),  # 278 ACR  SCREEN
    ('31226602-7845-47e0-8b7c-b1af21ad0f6d', 'T07'),  # 278 ACR  SCREEN
    ('7eed7fc0-15c7-4fa3-a3a8-d8e9347dfaf2', 'T08'),  # 278 ACR  BREACH
    ('6507ecde-1531-4d86-b3ec-d31729d5df0b', 'T09'),  # 278 ACR  SCREEN
    ('9aab7fe6-c7fb-4e74-b586-e11a00fc3eb9', 'T10'),  # 1-112 IN CRESRV, + (b) (h) (j)
    ('89ba4d53-212e-4839-93da-d9e0a16bc4c4', 'T11'),  # 1-112 IN CRESRV
    ('c6913c98-1713-4865-aaf5-415994cae4cf', 'T12'),  # 116 ABCT DESTRY - DROPPED (FULL_DROP)
    ('37677c40-c595-4b4c-9039-e9865abb4eb3', 'T13'),  # 48 IBCT  ExecutePlanPhase -> CNFPSL (g)
    ('1075b583-a7b8-45e5-b22b-d09988c9443e', 'T14'),  # 48 IBCT  ATTACK -> FOLSPT (f), (e) (i)
    ('71fbb065-dc1d-4e59-b3b4-37e0886841c5', 'T15'),  # 48 IBCT  CLRLND
    ('e84f2cc6-88a3-4630-8991-ca90b14a7969', 'T16'),  # 48 IBCT  SEIZE
    ('09145166-899f-4851-b271-43be741c2f52', 'T17'),  # 48 IBCT  RETAIN
    ('260e60ea-e624-4175-af30-52ce43c2675c', 'T18'),  # 55 MEB   RETAIN
    ('1d9f4ce2-2f3a-41ff-b5ab-577deaa01dcc', 'T19'),  # 55 MEB   SECURE
    ('acbac606-dc82-4101-ad9c-394b352e291c', 'T20'),  # 55 MEB   SECURE
    ('d691bea4-96e4-40bd-8e3d-999413d80197', 'T21'),  # 55 MEB   SECURE
    ('7c962730-9929-4a0c-ba3c-55c1b5213b75', 'T22'),  # 169 FAB  OCCUPY
    ('8645f7db-dd9d-4ae4-b035-0e2f61abf4b9', 'T23'),  # 11 CAB   DESTRY
)

# The ONE task the full variant drops, and why (data/IRONSTORM_FULL_CHANGES.md).
FULL_DROP = {
    'c6913c98-1713-4865-aaf5-415994cae4cf':
        'T12 116 ABCT DESTRY: a 52.6 km route (first leg 44.9 km) to Alytus over terrain tiles '
        'that are not cached - tier 2; no task depends on it',
}

KEEP_FULL = dict((u, label) for u, label in EXPORT_TASKS if u not in FULL_DROP)

# (g) covers T03 as well: its STP source is the third 'ConductFwdPassageOfLines' task (56 SBCT,
# how 'PASSAGE_OF_LINES', what 'NOT_SPECIFIED' - STP-IRON-STORM-SYNTHETIC_Narrative1.op), the same
# connector defect as T01 and T13. Cut A never kept T03, which is the only reason it was not listed.
CODE_FIX_FULL = dict(CODE_FIX)
CODE_FIX_FULL['4edbc258-07f9-4be4-991c-b3093b11e142'] = (
    'g', 'ExecutePlanPhase', 'CNFPSL', None, None, ':609/:645-646/:668')


def apply_code_fix(block, old_code, new_code, affected_uuid=None, affected_label=None):
    """(f)/(g) Replace the ONE TaskActionCode and, when affected_uuid is given, add ONE
    AffectedEntity line right after the exported (first) AffectedEntity. Raises unless
    each anchor occurs exactly once."""
    old = '<TaskActionCode>%s</TaskActionCode>' % old_code
    if block.count(old) != 1 or block.count('<TaskActionCode>') != 1:
        raise AssertionError('(f) expected exactly one %s in the task block' % old)
    if affected_uuid is None:
        return block.replace(old, '<TaskActionCode>%s</TaskActionCode>' % new_code)
    if affected_uuid in block:
        raise AssertionError('(f) the task already names %s' % affected_uuid)
    first = re.search(r'[ \t]*<AffectedEntity>[^<]*</AffectedEntity>[^\r\n]*\r\n', block)
    if not first or len(re.findall(r'<AffectedEntity>', block)) != 1:
        raise AssertionError('(f) expected exactly one exported AffectedEntity')
    line = ('%s<AffectedEntity>%s</AffectedEntity><!--%s ADDED BY CUT A (f)-->%s'
            % (INDENT, affected_uuid, affected_label, EOL))
    block = block[:first.end()] + line + block[first.end():]
    return block.replace(old, '<TaskActionCode>%s</TaskActionCode>' % new_code)

# ---------------------------------------------------------------------------
# (e) THE WATER NUDGE on T14's destination. USER RULING 2026-09-21 ("as recommended"):
# apply the 800 m-west destination nudge in the DERIVED file; STP will not re-author it.
#
# WHY. The authored leg 48 IBCT -> 54.04034819271516/23.336444730300467 crosses OPEN
# WATER: CLCplus (dataset 59, level 14) class 100, preset="Water", from 752 m to 2,346 m
# along a 2,757 m leg - 72 of 276 samples at a 10 m stride. `deep-water` is
# acceleration-factor 0.000000 in ground-tracked.sysdef, so a ground vehicle driven onto
# it STOPS and the vendor reports TaskRunning for ever. The lateral route shift cannot
# save it: the shift only fires on a leg FLAGGED for grade, and this leg's ratio is 0.10.
#
#   BEFORE  54.04034819271516  / 23.336444730300467
#   AFTER   54.040348          / 23.324206            (799 m due west)
#
# Measured dry at FOUR strides after the move - 25 m, 10 m, 5 m and 2 m (1,213 samples at
# 2 m, zero water) - because the original 25 m stride is coarse enough to step over a
# narrow inlet, and a dry verdict that depends on the stride is not a verdict.
#
# WHICH COPY IS AUTHORITATIVE. The interface drives the MAPGRAPHIC, not the embedded
# Location (TaskGeometryResolver returns GeometrySource.MapGraphic as soon as a graphic
# resolves). T14 names ONE graphic, 7351f662 FollowAndSupport_48_IBCT_SLOT1, a TaskGraphic
# with two vertices; under main's role-based resolver that is a LINE, its first vertex IS
# 48 IBCT's own position and is dropped at OriginCoincidenceMeters, and the SECOND vertex
# is the destination. So the graphic's second vertex is what had to move. T14's embedded
# Location carries the same pair and is moved WITH it so the two cannot disagree - the
# coordinate appears exactly twice in the derived order and both are rewritten.
# ---------------------------------------------------------------------------
NUDGE_FROM = ('54.04034819271516', '23.336444730300467')
NUDGE_TO = ('54.040348', '23.324206')
NUDGE_EXPECTED_SITES = 2       # the graphic's 2nd vertex + T14's embedded Location
NUDGE_GRAPHIC = '7351f662-f857-e05a-b533-f9a46e0fb095'
NUDGE_TASK = '1075b583-a7b8-45e5-b22b-d09988c9443e'


# ---------------------------------------------------------------------------
# (h) T10's REROUTE round two navigation-mesh sectors. OWNER SELECTION 2026-09-26
# ("Maples + reroute T10's leg around the two sectors (Recommended)").
#
# WHY. On the IRONSTORM-CENTRE nav area generated on the red-maple terrain (biome 04's
# Sycamore / White Oak -> RedMapleSpring; docs/experiments/PREREG_IRONSTORM_TREES_2026-09-26.md
# Part 2) T10's straight leg crosses sectors (28,21) 0.8485 and (28,22) 0.8857, below the
# 0.9 abstract-graph connectivity bar the owner set for every route sector. Both are
# lake-edge sectors (water 0.34 / 0.22); no tree lever clears (28,21) (0.818 / 0.849 / 0.862
# across three generations). The route goes round them instead.
#
# HOW, with the least new geometry: ONE new waypoint. T10 references ONE new Line/Route
# graphic whose two vertices are 1-112 IN's own init position and the waypoint, placed
# BEFORE the (b) PassagePoint reference, which stays the destination. The interface's
# route assembly (TaskGeometryResolver SF9 rule: lines supply the path, points the
# destination, and a line vertex within OriginCoincidenceMeters = 100 m of the taskee is
# dropped) turns that into the route  start -> WAYPOINT -> PassagePoint_48_IBCT_SLOT0.
# The first vertex being the taskee's own position is the export's own convention (T14's
# TaskGraphic 7351f662 starts at 48 IBCT's position). The unit's init position and the
# destination are asserted, not assumed. The only graphic this cut ADDS.
#
#   BEFORE  54.04268819191243/23.30823457011959 -> 54.019388734463774/23.313901568645093
#           (2,620 m straight; sectors (28,21) 0.8485 and (28,22) 0.8857 on the maple area)
#   AFTER   ... -> REROUTE_WAYPOINT -> ... (see CHANGES.md for the corridor and water checks)
# ---------------------------------------------------------------------------
REROUTE_TASK = '9aab7fe6-c7fb-4e74-b586-e11a00fc3eb9'          # T10
REROUTE_UNIT = '8d5b2ba6-73c1-6c55-812c-7c8078ea8c97'          # 1-112_IN/28ID
REROUTE_START = ('54.04268819191243', '23.30823457011959')     # its init position
REROUTE_DEST_GRAPHIC = 'cc23071f-aa60-9f52-884c-11505051cc99'  # (b) PassagePoint_48_IBCT_SLOT0
REROUTE_WAYPOINT = ('54.029734', '23.305499')
# uuid5(NAMESPACE_URL, 'urn:c2sim-vrf:IRONSTORM_CUTA:(h):T10-reroute:2026-09-26') - fixed,
# so the derivation stays byte-reproducible.
REROUTE_GRAPHIC = 'c8d9cd1a-b808-5b8d-97be-7beb98393a62'
REROUTE_NAME = 'T10_Reroute_1-112_IN__CUT_A_H_ROUTE_AROUND_SECTORS_28_21_28_22'


def reroute_entity():
    """The (h) graphic, in the export's own Line/Route layout (the axis-of-advance
    SIDC the export uses for its routes)."""
    return route_entity(REROUTE_NAME, REROUTE_GRAPHIC, REROUTE_START, REROUTE_WAYPOINT)


def route_entity(name, uuid_, start, waypoint):
    """One added two-vertex Line/Route graphic (changes (h) and (i))."""
    def loc(lat, lon):
        return ('                      <Location>' + EOL
                + '                        <GeodeticCoordinate>' + EOL
                + '                          <Latitude>%s</Latitude>' % lat + EOL
                + '                          <Longitude>%s</Longitude>' % lon + EOL
                + '                        </GeodeticCoordinate>' + EOL
                + '                      </Location>' + EOL)
    return ('      <Entity>' + EOL
            + '        <PhysicalEntity>' + EOL
            + '          <MapGraphic>' + EOL
            + '            <TacticalGraphic>' + EOL
            + '              <Line>' + EOL
            + '                <Route>' + EOL
            + '                  <APP6CSymbol>' + EOL
            + '                    <APP6C-SIDC>GFGPOLAGM-----X</APP6C-SIDC>' + EOL
            + '                  </APP6CSymbol>' + EOL
            + '                  <Name>%s</Name>' % name + EOL
            + '                  <SISOEntityType>' + EOL
            + ''.join('                    <%s>0</%s>' % (k, k) + EOL for k in (
                'DISCategory', 'DISCountry', 'DISDomain', 'DISExtra', 'DISKind',
                'DISSpecific', 'DISSubCategory'))
            + '                  </SISOEntityType>' + EOL
            + '                  <UUID>%s</UUID>' % uuid_ + EOL
            + '                  <CurrentState>' + EOL
            + '                    <PhysicalState>' + EOL
            + loc(*start) + loc(*waypoint)
            + '                    </PhysicalState>' + EOL
            + '                  </CurrentState>' + EOL
            + '                </Route>' + EOL
            + '              </Line>' + EOL
            + '            </TacticalGraphic>' + EOL
            + '          </MapGraphic>' + EOL
            + '        </PhysicalEntity>' + EOL
            + '      </Entity>' + EOL)


def apply_reroute(text, log, init_text):
    """(h) Add the reroute graphic right after the destination graphic's <Entity> and
    reference it from T10, before the (b) reference. Every anchor is asserted."""
    if REROUTE_GRAPHIC in text:
        raise AssertionError('(h) the reroute graphic %s is already present' % REROUTE_GRAPHIC)
    # the unit's init position must be exactly the line's first vertex
    at = init_text.find('<UUID>%s</UUID>' % REROUTE_UNIT) if init_text else -1
    if at < 0:
        raise AssertionError('(h) unit %s is not in the init' % REROUTE_UNIT)
    ent = init_text.rfind('<Entity>', 0, at)
    pos = re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>',
                     init_text[ent:at])
    if pos != [REROUTE_START]:
        raise AssertionError('(h) 1-112 IN init position is %r, expected %r' % (pos, REROUTE_START))
    # the destination graphic's Entity: insert after its closing tag
    g = text.find('<UUID>%s</UUID>' % REROUTE_DEST_GRAPHIC)
    if g < 0 or text.count('<UUID>%s</UUID>' % REROUTE_DEST_GRAPHIC) != 1:
        raise AssertionError('(h) expected the destination graphic exactly once')
    close = '      </Entity>' + EOL
    end = text.find(close, g)
    if end < 0:
        raise AssertionError('(h) no </Entity> after the destination graphic')
    end += len(close)
    text = text[:end] + reroute_entity() + text[end:]
    # T10's block: the new MapGraphicID goes right before the (b) one
    ref = (INDENT + '<MapGraphicID>%s</MapGraphicID><!--PassagePoint_48_IBCT_SLOT0 ADDED BY CUT A-->'
           % REROUTE_DEST_GRAPHIC)
    t10 = text.find('<UUID>%s</UUID>' % REROUTE_TASK)
    blk_start = text.rfind('<Task>', 0, t10)
    at_ref = text.find(ref, blk_start, t10)
    if at_ref < 0 or text.count(ref) != 1:
        raise AssertionError('(h) T10 does not carry the (b) reference exactly once')
    line = ('%s<MapGraphicID>%s</MapGraphicID><!--T10_Reroute ADDED BY CUT A (h)-->%s'
            % (INDENT, REROUTE_GRAPHIC, EOL))
    text = text[:at_ref] + line + text[at_ref:]
    log('  (h) T10 reroute: + Route graphic %s [%s,%s -> %s,%s] referenced before the (b) '
        'destination (OWNER SELECTION 2026-09-26; avoids nav sectors (28,21) / (28,22))'
        % (REROUTE_GRAPHIC[:8], REROUTE_START[0], REROUTE_START[1],
           REROUTE_WAYPOINT[0], REROUTE_WAYPOINT[1]))
    return text


# ---------------------------------------------------------------------------
# (i) T14 ROUTED ROUND THE LAKE Jezioro Wiersnie. 2026-09-27, lane T14 (pre-warm finding).
#
# WHY. In IRONSTORM_CUTA_LIVE-2026-09-27-1's pre-warm (runs/20260927T003120Z_run) 48 IBCT drove
# 850 m of the (e)-nudged leg and stopped dead at 54.026779 / 23.317195 for the rest of the run,
# console silent. That point is 0.5 m outside OSM way 197345448 (natural=water, "Jezioro
# Wiersnie"), which the vendor's land-cover composite puts on TOP of CLCplus
# (biomes.landcover.coverage.online.xml:58, sim-enabled by biome.config.online.xml:13):
# selectStyle() default -> coverage value 80 -> preset Water -> BM_WATER
# (layer.OSM.water.LOD14.online.xml, presets.xml:36) -> deeplake (landCoverDataSurfChar.map:346)
# -> deep-water (UG52 Table 26) -> acceleration-factor 0.000000 (ground-tracked.sysdef:813-815).
# (e) was checked dry against CLCplus ONLY; the nudged centreline enters the OSM polygon at 834 m.
#
# HOW, the (h) pattern: ONE waypoint on ONE added Line/Route graphic whose vertices are 48 IBCT's
# own init position (asserted) and the waypoint, referenced by T14 BEFORE its FollowAndSupport
# graphic 7351f662. The resolver drops both graphics' first vertex (the taskee's own position)
# and chains nearest-first: start -> WAYPOINT -> 54.040348 / 23.324206 (the (e) destination,
# UNCHANGED). The west side of the lake was searched first and rejected: every dry west route
# either crosses nav sectors (28,21)/(28,22) (0.8485) or runs head-on down T10's own corridor,
# where T10's seven members were still crawling in the pre-warm.
#
# SEMANTICS. T14 stays FOLSPT ("advance along the task's graphic to its end and hold",
# TaskDispatchPolicy.cs:57). The hold point is unchanged; the PATH is no longer the
# FollowAndSupport graphic's straight line - it now bends through a waypoint that is not on
# that graphic.
# ---------------------------------------------------------------------------
T14WP_TASK = '1075b583-a7b8-45e5-b22b-d09988c9443e'            # T14
T14WP_UNIT = 'dd3d21b2-c5e0-d45a-9fba-b4b8bb879e6a'            # 48_IBCT/28ID
T14WP_START = ('54.019388734463774', '23.313901568645093')     # its init position
T14WP_FOLLOW_GRAPHIC = '7351f662-f857-e05a-b533-f9a46e0fb095'  # FollowAndSupport_48_IBCT_SLOT1
T14WP_WAYPOINT = ('54.014600', '23.331500')
# uuid5(NAMESPACE_URL, 'urn:c2sim-vrf:IRONSTORM_CUTA:(i):T14-waypoint:2026-09-27')
T14WP_GRAPHIC = '7ff48b93-5a1e-5a9a-813f-8dda1df7e5dd'
T14WP_NAME = 'T14_Waypoint_48_IBCT__CUT_A_I_ROUTE_ROUND_LAKE_SE'


def unit_init_position(init_text, unit_uuid):
    """The (lat, lon) strings of a unit's init <Entity>, asserted to be exactly one pair."""
    at = init_text.find('<UUID>%s</UUID>' % unit_uuid) if init_text else -1
    if at < 0:
        raise AssertionError('unit %s is not in the init' % unit_uuid)
    ent = init_text.rfind('<Entity>', 0, at)
    pos = re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>',
                     init_text[ent:at])
    if len(pos) != 1:
        raise AssertionError('unit %s carries %d init position(s)' % (unit_uuid, len(pos)))
    return pos[0]


def t14_waypoint_entity():
    """The (i) graphic's <Entity> text, exactly as apply_t14_waypoint inserts it."""
    return route_entity(T14WP_NAME, T14WP_GRAPHIC, T14WP_START, T14WP_WAYPOINT)


def t14_waypoint_ref():
    """The (i) MapGraphicID line, exactly as apply_t14_waypoint inserts it into T14's block."""
    return ('%s<MapGraphicID>%s</MapGraphicID><!--T14_Waypoint ADDED BY CUT A (i)-->%s'
            % (INDENT, T14WP_GRAPHIC, EOL))


def apply_t14_waypoint(text, log, init_text):
    """(i) Add T14's waypoint graphic right after the FollowAndSupport graphic's <Entity> and
    reference it from T14, before the FollowAndSupport reference. Every anchor is asserted."""
    if T14WP_GRAPHIC in text:
        raise AssertionError('(i) the waypoint graphic %s is already present' % T14WP_GRAPHIC)
    pos = unit_init_position(init_text, T14WP_UNIT)
    if pos != T14WP_START:
        raise AssertionError('(i) 48 IBCT init position is %r, expected %r' % (pos, T14WP_START))
    g = text.find('<UUID>%s</UUID>' % T14WP_FOLLOW_GRAPHIC)
    if g < 0 or text.count('<UUID>%s</UUID>' % T14WP_FOLLOW_GRAPHIC) != 1:
        raise AssertionError('(i) expected the FollowAndSupport graphic exactly once')
    # its first vertex must be the taskee's own position (the resolver drops it) and its last
    # the (e) destination - otherwise the assembled route is not start -> WP -> destination
    blk = text[g:text.find('</TaskGraphic>', g)]
    verts = re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>', blk)
    if verts != [T14WP_START, NUDGE_TO]:
        raise AssertionError('(i) FollowAndSupport vertices are %r, expected [start, (e) '
                             'destination]' % (verts,))
    close = '      </Entity>' + EOL
    end = text.find(close, g)
    if end < 0:
        raise AssertionError('(i) no </Entity> after the FollowAndSupport graphic')
    end += len(close)
    text = text[:end] + t14_waypoint_entity() + text[end:]
    ref = (INDENT + '<MapGraphicID>%s</MapGraphicID><!--FollowAndSupport_48_IBCT_SLOT1-->'
           % T14WP_FOLLOW_GRAPHIC)
    t14 = text.find('<UUID>%s</UUID>' % T14WP_TASK)
    blk_start = text.rfind('<Task>', 0, t14)
    at_ref = text.find(ref, blk_start, t14)
    if t14 < 0 or at_ref < 0 or text.count(ref) != 1:
        raise AssertionError('(i) T14 does not carry the FollowAndSupport reference exactly once')
    text = text[:at_ref] + t14_waypoint_ref() + text[at_ref:]
    log('  (i) T14 waypoint: + Route graphic %s [%s,%s -> %s,%s] referenced before the '
        'FollowAndSupport graphic (routes round Jezioro Wiersnie, OSM way 197345448; '
        'destination unchanged)'
        % (T14WP_GRAPHIC[:8], T14WP_START[0], T14WP_START[1],
           T14WP_WAYPOINT[0], T14WP_WAYPOINT[1]))
    return text


# ---------------------------------------------------------------------------
# (j) T10's (h) LEG 2 KEPT OFF A POND. 2026-09-27, lane T10 (found by lane T14's OSM-aware check).
#
# WHY. (h)'s second leg, waypoint 54.029734 / 23.305499 -> PassagePoint_48_IBCT_SLOT0, runs down
# the east edge of an OSM natural=water pond (coverage value 80 -> deep-water, the chain (i)
# documents): 1 centreline sample at 54.02359 / 23.31049, and 81 / 102 samples at 25 / 50 m right
# of travel (702-880 m along). 1-112 IN is a six-to-seven member aggregate moving in formation,
# so its right-hand members would drive into it. (h) was checked dry on CLCplus only.
#
# HOW, the (h)/(i) pattern: ONE more waypoint, east of the pond, on ONE added Line/Route graphic
# whose vertices are 1-112 IN's own init position (asserted) and the waypoint, referenced by T10
# AFTER the (h) reroute and BEFORE the (b) PassagePoint. The resolver drops both lines' first
# vertex (the taskee's own position) and chains nearest-first from the taskee: the (h) waypoint
# is nearer, so the route is start -> (h) WP -> (j) WP -> PassagePoint (asserted below from the
# distances, since the order of the MapGraphicIDs does not decide it). Leg 1 and the destination
# are UNCHANGED.
# ---------------------------------------------------------------------------
T10WP_WAYPOINT = ('54.024000', '23.313000')
# uuid5(NAMESPACE_URL, 'urn:c2sim-vrf:IRONSTORM_CUTA:(j):T10-leg2-waypoint:2026-09-27')
T10WP_GRAPHIC = '51a59f89-799e-5ed0-8c05-1e63b01e8069'
T10WP_NAME = 'T10_Waypoint_1-112_IN__CUT_A_J_KEEP_LEG_2_OFF_POND'


def _dist_m(a, b):
    """Equirectangular metres between two (lat, lon) string/float pairs - ample for ordering
    points 0.5-3 km apart."""
    la1, lo1, la2, lo2 = (float(a[0]), float(a[1]), float(b[0]), float(b[1]))
    k = math.cos(math.radians((la1 + la2) / 2.0))
    return math.hypot((lo2 - lo1) * 111320.0 * k, (la2 - la1) * 111320.0)


def apply_t10_waypoint(text, log, init_text):
    """(j) Add T10's second waypoint graphic right after the (h) reroute graphic's <Entity> and
    reference it from T10, after the (h) reference and before the (b) destination. Every
    anchor is asserted, and so is the chaining order the resolver will derive."""
    if T10WP_GRAPHIC in text:
        raise AssertionError('(j) the waypoint graphic %s is already present' % T10WP_GRAPHIC)
    pos = unit_init_position(init_text, REROUTE_UNIT)
    if pos != REROUTE_START:
        raise AssertionError('(j) 1-112 IN init position is %r, expected %r' % (pos, REROUTE_START))
    # the (h) graphic must be there and still be [start, (h) waypoint]
    g = text.find('<UUID>%s</UUID>' % REROUTE_GRAPHIC)
    if g < 0 or text.count('<UUID>%s</UUID>' % REROUTE_GRAPHIC) != 1:
        raise AssertionError('(j) expected the (h) reroute graphic exactly once - apply (h) first')
    blk = text[g:text.find('</Route>', g)]
    verts = re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>', blk)
    if verts != [REROUTE_START, REROUTE_WAYPOINT]:
        raise AssertionError('(j) the (h) graphic vertices are %r, expected [start, (h) waypoint]'
                             % (verts,))
    # nearest-first chaining must put the (h) waypoint first: start -> (h) -> (j) -> destination
    if not _dist_m(REROUTE_START, REROUTE_WAYPOINT) < _dist_m(REROUTE_START, T10WP_WAYPOINT):
        raise AssertionError('(j) the (j) waypoint is nearer the start than the (h) one; the '
                             'resolver would chain it first')
    close = '      </Entity>' + EOL
    end = text.find(close, g)
    if end < 0:
        raise AssertionError('(j) no </Entity> after the (h) reroute graphic')
    end += len(close)
    text = (text[:end] + route_entity(T10WP_NAME, T10WP_GRAPHIC, REROUTE_START, T10WP_WAYPOINT)
            + text[end:])
    # T10's block: (h) reference, then (j), then the (b) destination
    ref_h = ('%s<MapGraphicID>%s</MapGraphicID><!--T10_Reroute ADDED BY CUT A (h)-->%s'
             % (INDENT, REROUTE_GRAPHIC, EOL))
    ref_b = (INDENT + '<MapGraphicID>%s</MapGraphicID><!--PassagePoint_48_IBCT_SLOT0 ADDED BY CUT A-->'
             % REROUTE_DEST_GRAPHIC)
    t10 = text.find('<UUID>%s</UUID>' % REROUTE_TASK)
    blk_start = text.rfind('<Task>', 0, t10)
    at_h = text.find(ref_h, blk_start, t10)
    at_b = text.find(ref_b, blk_start, t10)
    if (t10 < 0 or at_h < 0 or at_b < 0 or text.count(ref_h) != 1 or text.count(ref_b) != 1
            or at_h + len(ref_h) != at_b):
        raise AssertionError('(j) T10 does not carry the (h) reference immediately before the (b) '
                             'destination, exactly once')
    line = ('%s<MapGraphicID>%s</MapGraphicID><!--T10_Waypoint ADDED BY CUT A (j)-->%s'
            % (INDENT, T10WP_GRAPHIC, EOL))
    text = text[:at_b] + line + text[at_b:]
    log('  (j) T10 waypoint: + Route graphic %s [%s,%s -> %s,%s] referenced after (h), before the '
        '(b) destination (keeps (h) leg 2 off an OSM pond; destination unchanged)'
        % (T10WP_GRAPHIC[:8], REROUTE_START[0], REROUTE_START[1],
           T10WP_WAYPOINT[0], T10WP_WAYPOINT[1]))
    return text


# ---------------------------------------------------------------------------
# VARIANTS - a change LEFT OUT, only where a registered run needs it. 2026-09-27, run E1.
#
# WHY. RL-20260927-01 ("Go", docs/PLAN_MOVEMENT_2026-09-27.md): a LONE ground platform is now
# driven by Move To per STP vertex, and Move To PLANS each leg - roads, the nav mesh, round
# feature obstacles - and recovers from a blockage (UG52 23.1-23.2), where Move Along Route
# drove STP's straight line and planned nothing (UG52 23.3). Change (i) is a hand-placed
# waypoint that did the planner's job for T14. Run E1 takes it away on purpose: T14 drives its
# ORIGINAL line, whose centreline enters the OSM lake at 834 m, and the PLANNER has to take it
# round. The (e) destination stays (it moved the END POINT out of the lake, and Move To cannot
# end in water either, FINDING_GROUND_MOVEMENT_PRACTICE_2026-09-27 sec 5.2).
#
# RULES. A variant is a named, registered output file - never an ad-hoc edit. Only the letters
# in a VARIANTS key may be left out; anything else is refused, so a typo cannot produce a
# plausible wrong order. (k) (T14 round the hamlet) lives on the unmerged branch
# fix/ironstorm-t14-hamlet and is not a change of this derivation.
# ---------------------------------------------------------------------------
CHANGE_LETTERS = 'abcdefghij'      # every change of THIS derivation, (a)-(j)

VARIANTS = {                       # changes left out -> the order file it is written to
    frozenset(): OUT_ORDER,        # the cut as ruled: (a)-(j)
    frozenset('i'): OUT_ORDER_E1,  # run E1: T14 on its ORIGINAL line, (a)-(h) and (j)
}


def variant_label(without):
    """A variant's name in log lines: 'as ruled, (a)-(j)' or 'without (i)'."""
    if not without:
        return 'as ruled, (a)-(j)'
    return 'without %s' % ', '.join('(%s)' % c for c in sorted(without))


def parse_without(spec):
    """The --without text -> the frozenset of change letters to leave out ('' = none).
    Letters are comma-separated. Every letter must be a change of this derivation, lower-case,
    and the resulting set must be a REGISTERED variant; anything else raises ValueError - the
    script never guesses which order was meant."""
    text = (spec or '').strip()
    if not text:
        return frozenset()
    letters = set()
    for tok in text.split(','):
        tok = tok.strip()
        if len(tok) != 1 or tok not in CHANGE_LETTERS:
            raise ValueError('unknown change letter %r - this derivation has (%s)%s'
                             % (tok, ') ('.join(CHANGE_LETTERS),
                                '; (k) is on the unmerged branch fix/ironstorm-t14-hamlet'
                                if tok.lower() == 'k' else ''))
        letters.add(tok)
    key = frozenset(letters)
    if key not in VARIANTS:
        raise ValueError('no registered variant leaves out %s; the registered variants are: %s'
                         % (', '.join('(%s)' % c for c in sorted(key)),
                            '; '.join(variant_label(v) for v in sorted(VARIANTS, key=len))))
    return key


def assert_t14_original_line(text, init_text):
    """The E1 variant's claim, CHECKED rather than assumed: T14 names exactly ONE MapGraphicID,
    the FollowAndSupport graphic, whose vertices are [48 IBCT's init position, the (e)
    destination] - so the resolver drops the first and T14 drives start -> (e) destination - and
    the (i) waypoint graphic is nowhere in the order."""
    if T14WP_GRAPHIC in text:
        raise AssertionError('(i) left out, but its waypoint graphic %s is in the order'
                             % T14WP_GRAPHIC)
    pos = unit_init_position(init_text, T14WP_UNIT)
    if pos != T14WP_START:
        raise AssertionError('48 IBCT init position is %r, expected %r' % (pos, T14WP_START))
    g = text.find('<UUID>%s</UUID>' % T14WP_FOLLOW_GRAPHIC)
    if g < 0 or text.count('<UUID>%s</UUID>' % T14WP_FOLLOW_GRAPHIC) != 1:
        raise AssertionError('expected the FollowAndSupport graphic exactly once')
    blk = text[g:text.find('</TaskGraphic>', g)]
    verts = re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>', blk)
    if verts != [T14WP_START, NUDGE_TO]:
        raise AssertionError('FollowAndSupport vertices are %r, expected [start, (e) destination]'
                             % (verts,))
    t14 = text.find('<UUID>%s</UUID>' % T14WP_TASK)
    if t14 < 0:
        raise AssertionError('T14 is not in the order')
    refs = re.findall(r'<MapGraphicID>([^<]*)</MapGraphicID>',
                      text[text.rfind('<Task>', 0, t14):t14])
    if refs != [T14WP_FOLLOW_GRAPHIC]:
        raise AssertionError('T14 names MapGraphicID(s) %r, expected only the FollowAndSupport '
                             'graphic %s' % (refs, T14WP_FOLLOW_GRAPHIC))


def remove_change_i(text):
    """The inverse of apply_t14_waypoint on a derived order: remove its ONE added graphic
    <Entity> and its ONE added MapGraphicID line, each asserted to occur exactly once. Every run
    uses it to prove the without-(i) order is the full order minus (i) and NOTHING else."""
    for label, piece in (('the (i) graphic entity', t14_waypoint_entity()),
                         ('the (i) MapGraphicID line', t14_waypoint_ref())):
        n = text.count(piece)
        if n != 1:
            raise AssertionError('%s occurs %d time(s), expected exactly 1' % (label, n))
        text = text.replace(piece, '')
    return text


def apply_added_graphics(text, log, init_text, without=frozenset()):
    """(h), then (i) unless the variant leaves it out, then (j) - the three added graphics, in
    the order derive_order has always applied them. (j) does not depend on (i)."""
    # (h) the T10 reroute (after (b) put the destination reference in T10's block).
    text = apply_reroute(text, log, init_text)
    # (i) T14's waypoint round the lake (after (e) put the destination on the graphic).
    if 'i' in without:
        assert_t14_original_line(text, init_text)
        log('  (i) LEFT OUT (--without i, run E1): T14 keeps its ORIGINAL line - the '
            'FollowAndSupport graphic %s only, [%s,%s -> %s,%s]; the (e) destination stays'
            % (T14WP_FOLLOW_GRAPHIC[:8], T14WP_START[0], T14WP_START[1],
               NUDGE_TO[0], NUDGE_TO[1]))
    else:
        text = apply_t14_waypoint(text, log, init_text)
    # (j) T10's second waypoint, keeping (h) leg 2 off the pond (after (h) added its graphic).
    text = apply_t10_waypoint(text, log, init_text)
    return text


# ---------------------------------------------------------------------------
# (a) the duration rewrite - a pure function, self-tested below
# ---------------------------------------------------------------------------
C2SIM_DURATION = re.compile(
    r'^P[0-9]{2}Y[0-9]{2}M[0-9]{2}DT[0-9]{2}H[0-9]{2}M[0-9]{2}S$')

# canonical ISO-8601: PnYnMnDTnHnMnS with any field omitted. Fractions are NOT accepted -
# the C2SIM pattern has no room for them, so silently truncating one would change a value.
ISO_8601 = re.compile(
    r'^P(?:([0-9]+)Y)?(?:([0-9]+)M)?(?:([0-9]+)D)?'
    r'(?:T(?:([0-9]+)H)?(?:([0-9]+)M)?(?:([0-9]+)S)?)?$')


def to_c2sim_duration(value):
    """Rewrite an ISO-8601 duration into the C2SIM 1.1 pattern form.

    Already-conforming values are returned unchanged. Anything that cannot be read as a
    whole-number ISO-8601 duration, or whose fields do not fit two digits, raises - the
    point of this script is that a format it does not understand STOPS it, rather than
    being passed through to produce a plausible wrong time.
    """
    v = (value or '').strip()
    if C2SIM_DURATION.match(v):
        return v
    m = ISO_8601.match(v)
    if not m or v in ('P', 'PT'):
        raise ValueError('not an ISO-8601 duration this script can rewrite: %r' % value)
    y, mo, d, h, mi, s = (int(g) if g else 0 for g in m.groups())
    for label, n in (('years', y), ('months', mo), ('days', d),
                     ('hours', h), ('minutes', mi), ('seconds', s)):
        if n > 99:
            raise ValueError('%s=%d does not fit the C2SIM two-digit field in %r'
                             % (label, n, value))
    return 'P%02dY%02dM%02dDT%02dH%02dM%02dS' % (y, mo, d, h, mi, s)


def rewrite_durations(text):
    """Rewrite every IsoTimeDuration element value in place. Returns (text, changes)."""
    changes = []

    def sub(m):
        old = m.group(1)
        new = to_c2sim_duration(old)
        if new != old:
            changes.append((old, new))
        return '<IsoTimeDuration>%s</IsoTimeDuration>' % new

    out = re.sub(r'<IsoTimeDuration>([^<]*)</IsoTimeDuration>', sub, text)
    return out, changes


# ---------------------------------------------------------------------------
# task blocks
# ---------------------------------------------------------------------------
TASK_BLOCK = re.compile(r'[ \t]*<Task>\r\n.*?[ \t]*</Task>\r\n', re.S)


def task_uuid(block):
    m = re.search(r'<UUID>([^<]+)</UUID>', block)
    return m.group(1).strip() if m else None


def apply_water_nudge(text, log):
    """(e) Move T14's destination 799 m due west, out of the lake. Pure text surgery on the
    ONE coordinate pair, asserted to appear exactly twice - the graphic vertex the
    interface drives and T14's embedded Location that mirrors it.

    Everything is checked rather than assumed: the pair must appear exactly
    NUDGE_EXPECTED_SITES times, the target longitude must not already be present, and
    afterwards BOTH the graphic block and the task block must carry the new value. Any of
    those failing raises, because a half-applied nudge would leave the driven route and
    the embedded route disagreeing - which is precisely the class of defect this script
    exists to make impossible.
    """
    old_lat, old_lon = NUDGE_FROM
    new_lat, new_lon = NUDGE_TO
    pair_old = ('<Latitude>%s</Latitude>' % old_lat, '<Longitude>%s</Longitude>' % old_lon)
    n_lat = text.count(pair_old[0])
    n_lon = text.count(pair_old[1])
    if n_lat != NUDGE_EXPECTED_SITES or n_lon != NUDGE_EXPECTED_SITES:
        raise AssertionError('(e) expected the destination pair %s/%s exactly %d time(s); '
                             'found lat x%d, lon x%d - the export has changed shape'
                             % (old_lat, old_lon, NUDGE_EXPECTED_SITES, n_lat, n_lon))
    if ('<Longitude>%s</Longitude>' % new_lon) in text:
        raise AssertionError('(e) the target longitude %s is already present' % new_lon)

    text = text.replace(pair_old[0], '<Latitude>%s</Latitude>' % new_lat)
    text = text.replace(pair_old[1], '<Longitude>%s</Longitude>' % new_lon)

    # Both sites must really have moved: the graphic the interface drives, and the task.
    for label, uuid in (('graphic %s' % NUDGE_GRAPHIC[:8], NUDGE_GRAPHIC),
                        ('task %s (T14)' % NUDGE_TASK[:8], NUDGE_TASK)):
        at = text.find('<UUID>%s</UUID>' % uuid)
        if at < 0:
            raise AssertionError('(e) %s vanished from the derived order' % label)
        start = max(0, at - 4000)
        window = text[start:at + 4000]
        if ('<Longitude>%s</Longitude>' % new_lon) not in window:
            raise AssertionError('(e) %s does not carry the nudged longitude' % label)
    log('  (e) T14 destination %s,%s -> %s,%s  (799 m due west, out of the lake; '
        'USER RULING 2026-09-21) - %d site(s): the driven MapGraphic vertex and the '
        'mirrored embedded Location'
        % (old_lat, old_lon, new_lat, new_lon, NUDGE_EXPECTED_SITES))
    return text


def insert_map_graphic(block, graphic_uuid, short_name):
    """Insert one MapGraphicID immediately before Name - where the schema's ActionGroup
    sequence puts it (ActionTemporalRelationship, Location*, MapGraphicID*, Name, UUID).
    The annotation comment matches the style the export uses on every other
    MapGraphicID, and carries no '<word' token (the C2SIM SDK's DetermineProtocol reads
    the first '<'+letter ANYWHERE in the text, comments included - STP-830)."""
    needle = INDENT + '<Name>'
    at = block.find(needle)
    if at < 0:
        raise AssertionError('no <Name> at the expected indent in task block')
    line = ('%s<MapGraphicID>%s</MapGraphicID><!--%s ADDED BY CUT A-->%s'
            % (INDENT, graphic_uuid, short_name, EOL))
    return block[:at] + line + block[at:]


# ---------------------------------------------------------------------------
# gates
# ---------------------------------------------------------------------------
def gate(text, label, problems):
    """Every hazard this project has actually been bitten by, checked on the OUTPUT."""
    # ASCII only (control characters included - a stray VT/BEL is not printable ASCII)
    bad = [(i, c) for i, c in enumerate(text)
           if not (c in '\t\r\n' or ' ' <= c <= '~')]
    if bad:
        problems.append('%s: %d non-ASCII/control byte(s), first at offset %d (0x%02X)'
                        % (label, len(bad), bad[0][0], ord(bad[0][1])))
    # CRLF class preserved: no lone LF, no lone CR
    if re.search(r'(?<!\r)\n', text):
        problems.append('%s: a bare LF (the export is 100%% CRLF)' % label)
    if re.search(r'\r(?!\n)', text):
        problems.append('%s: a stray CR' % label)
    # STP-830: the SDK takes the first '<'+letter in the TEXT - comments included - as the
    # message root. Nothing may precede MessageBody, and no comment may hold such a token.
    first = re.search(r'<[A-Za-z_]', text)
    if not first or not text.startswith('<?xml', 0) or text[first.start():first.start() + 12] != '<MessageBody':
        problems.append('%s: the first "<word" token is not <MessageBody' % label)
    for c in re.findall(r'<!--(.*?)-->', text, re.S):
        if re.search(r'<[A-Za-z_]', c):
            problems.append('%s: an XML comment carries a "<word" token: %r' % (label, c[:60]))
    # well-formed, right root, right namespace
    try:
        root = ET.fromstring(text)
    except Exception as exc:                                   # noqa: BLE001
        problems.append('%s: not well-formed XML: %s' % (label, exc))
        return
    if root.tag != Q + 'MessageBody':
        problems.append('%s: root is %s, expected %sMessageBody' % (label, root.tag, Q))
    for v in re.findall(r'<IsoTimeDuration>([^<]*)</IsoTimeDuration>', text):
        if not C2SIM_DURATION.match(v):
            problems.append('%s: IsoTimeDuration %r still violates the C2SIM pattern'
                            % (label, v))


def sha(data):
    return hashlib.sha256(data if isinstance(data, bytes)
                          else data.encode('utf-8')).hexdigest()


def read(path):
    with open(path, 'r', encoding='utf-8', newline='') as fh:
        return fh.read()


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='') as fh:
        fh.write(text)


# ---------------------------------------------------------------------------
def derive_order(src_text, log, init_text=None, without=frozenset(), keep=None, code_fix=None):
    """Apply (a), (b), (c), (e), (f), (g), (h), (i) and (j) to the order text, minus the changes
    `without` names - which must be a REGISTERED variant (VARIANTS). Returns the derived text.
    `keep` / `code_fix` default to cut A's KEEP / CODE_FIX; the FULL variant passes KEEP_FULL /
    CODE_FIX_FULL (derive_order_full) - every other step is the same code."""
    keep = KEEP if keep is None else keep
    code_fix = CODE_FIX if code_fix is None else code_fix
    if frozenset(without) not in VARIANTS:
        raise AssertionError('no registered variant leaves out %r' % sorted(without))
    blocks = TASK_BLOCK.findall(src_text)
    log('order carries %d <Task> blocks' % len(blocks))
    if len(blocks) != src_text.count('<Task>'):
        raise AssertionError('the Task-block scanner missed %d of %d blocks'
                             % (src_text.count('<Task>') - len(blocks),
                                src_text.count('<Task>')))

    by_uuid = {}
    for b in blocks:
        u = task_uuid(b)
        if u is None:
            raise AssertionError('a <Task> block carries no <UUID>')
        if u in by_uuid:
            raise AssertionError('duplicate task uuid %s' % u)
        by_uuid[u] = b

    missing = sorted(set(keep) - set(by_uuid))
    if missing:
        raise AssertionError('the export no longer carries kept task(s): %s'
                             % ', '.join(missing))

    # (c) chain integrity: every kept task's predecessor must also be kept.
    for u in keep:
        m = re.search(r'<TemporalAssociationWithAction>([^<]+)<', by_uuid[u])
        pred = m.group(1).strip() if m else None
        if pred and pred not in keep:
            raise AssertionError('kept task %s (%s) depends on dropped task %s'
                                 % (keep[u], u, pred))
        log('  keep %s %s  predecessor=%s' % (keep[u], u, keep.get(pred, '-')))

    # (b) verify each added graphic EXISTS in the order, is a Point, and carries the Name
    # this script expects; then verify the task does not already reference it.
    for task_u, (g_uuid, g_name, _short) in ADD_GRAPHIC.items():
        at = src_text.find('<UUID>%s</UUID>' % g_uuid)
        if at < 0:
            raise AssertionError('graphic %s is not in the order' % g_uuid)
        start = src_text.rfind('<TacticalGraphic>', 0, at)
        end = src_text.find('</TacticalGraphic>', at)
        blk = src_text[start:end]
        if '<Point>' not in blk:
            raise AssertionError('graphic %s is not a <Point>' % g_uuid)
        nm = re.search(r'<Name>([^<]*)</Name>', blk)
        if not nm or nm.group(1).strip() != g_name:
            raise AssertionError('graphic %s Name is %r, expected %r'
                                 % (g_uuid, nm.group(1) if nm else None, g_name))
        if g_uuid in by_uuid[task_u]:
            raise AssertionError('task %s already references %s' % (keep[task_u], g_uuid))
        lat = re.search(r'<Latitude>([^<]*)</Latitude>', blk)
        lon = re.search(r'<Longitude>([^<]*)</Longitude>', blk)
        log('  add  %s -> %s  %s  @ %s, %s'
            % (keep[task_u], g_uuid, g_name[:34], lat.group(1), lon.group(1)))

    # Build the derived text: walk the ORIGINAL string, copying everything, replacing the
    # kept task blocks with their edited form and deleting the rest. Working on the raw
    # string (never on a re-serialized tree) is what keeps every untouched byte identical.
    out = []
    pos = 0
    kept = dropped = 0
    for m in TASK_BLOCK.finditer(src_text):
        out.append(src_text[pos:m.start()])
        pos = m.end()
        block = m.group(0)
        u = task_uuid(block)
        if u not in keep:
            dropped += 1
            continue
        if u in ADD_GRAPHIC:
            g_uuid, _g_name, short = ADD_GRAPHIC[u]
            block = insert_map_graphic(block, g_uuid, short)
        if u in code_fix:
            letter, old_c, new_c, aff, label, stp_lines = code_fix[u]
            if aff is not None and (init_text is None
                                    or ('<UUID>%s</UUID>' % aff) not in init_text):
                raise AssertionError('(f) %s (%s) is not a unit of the init - not inventing it'
                                     % (label, aff))
            block = apply_code_fix(block, old_c, new_c, aff, label)
            extra = '; AffectedEntity + %s %s' % (aff, label) if aff else ''
            log('  (%s) %s TaskActionCode %s -> %s%s (owner direction 2026-09-26; STP '
                'C2SimTask.cs%s case mismatch)' % (letter, keep[u], old_c, new_c, extra,
                                                    stp_lines))
        out.append(block)
        kept += 1
    out.append(src_text[pos:])
    text = ''.join(out)
    log('kept %d task(s), dropped %d' % (kept, dropped))
    if kept != len(keep):
        raise AssertionError('kept %d tasks, expected %d' % (kept, len(keep)))

    # (e) the water nudge, on the assembled document so the site count is the DERIVED
    # file's and not the export's.
    text = apply_water_nudge(text, log)

    # (h), (i) unless the variant leaves it out, (j) - see apply_added_graphics.
    text = apply_added_graphics(text, log, init_text, frozenset(without))

    # (a) last, so it covers the whole derived document including nothing new (the
    # inserted lines carry no duration).
    text, changes = rewrite_durations(text)
    log('rewrote %d IsoTimeDuration value(s)' % len(changes))
    seen = {}
    for old, new in changes:
        seen.setdefault((old, new), 0)
        seen[(old, new)] += 1
    for (old, new), n in sorted(seen.items()):
        log('  %-6s -> %-22s x%d' % (old, new, n))
    return text


FULL_DURATIONS = 44                # the export's 46 minus T12's two (its Duration and its StartTime)


def derive_order_full(src_text, log, init_text):
    """THE FULL VARIANT: the export's task list is ASSERTED to be EXPORT_TASKS (same uuids, same
    order), then derive_order runs with KEEP_FULL / CODE_FIX_FULL - all changes, every task but T12.
    The duration count is asserted: (a) must have rewritten all 44 values that remain."""
    found = tuple(task_uuid(b) for b in TASK_BLOCK.findall(src_text))
    want = tuple(u for u, _label in EXPORT_TASKS)
    if found != want:
        raise AssertionError('the export task list changed: %d task(s), expected the %d of '
                             'EXPORT_TASKS in order (first difference at #%d)'
                             % (len(found), len(want),
                                next((i + 1 for i, (a, b) in enumerate(zip(found, want)) if a != b),
                                     min(len(found), len(want)) + 1)))
    for u, why in sorted(FULL_DROP.items()):
        log('  drop %s %s  (%s)' % (dict(EXPORT_TASKS)[u], u, why))
    text = derive_order(src_text, log, init_text, frozenset(), KEEP_FULL, CODE_FIX_FULL)
    n = len(re.findall(r'<IsoTimeDuration>', text))
    if n != FULL_DURATIONS:
        raise AssertionError('the full order carries %d IsoTimeDuration value(s), expected %d'
                             % (n, FULL_DURATIONS))
    return text


def strip_tasks(text):
    """The document with every <Task> block removed - what two derivations must share."""
    return TASK_BLOCK.sub('', text)


def assert_full_extends_cuta(full_text, cuta_text):
    """The full order is the cut-A order PLUS the other tasks and NOTHING else: with every <Task>
    block removed the two are byte-identical, and each of cut A's task blocks occurs verbatim, once,
    in the full order. So everything a cut-A run established about T01/T02/T10/T13/T14 and the
    graphics carries over to the full order unchanged."""
    if strip_tasks(full_text) != strip_tasks(cuta_text):
        raise AssertionError('the full and cut-A orders differ OUTSIDE their task blocks')
    for b in TASK_BLOCK.findall(cuta_text):
        n = full_text.count(b)
        if n != 1:
            raise AssertionError('cut-A task %s occurs %d time(s) verbatim in the full order, '
                                 'expected 1' % (KEEP.get(task_uuid(b), task_uuid(b)), n))
    kept = [task_uuid(b) for b in TASK_BLOCK.findall(full_text)]
    if kept != [u for u, _label in EXPORT_TASKS if u in KEEP_FULL]:
        raise AssertionError('the full order does not carry KEEP_FULL in export order')


def derive_init(src_text, log):
    """The init needs NO change: it carries no IsoTimeDuration (verified here, not
    assumed), no task, and its SystemName is left exactly as exported - (d). The derived
    file is therefore a byte-identical copy under the cut's own name."""
    n = len(re.findall(r'<IsoTimeDuration>', src_text))
    if n:
        raise AssertionError('the init now carries %d IsoTimeDuration value(s); change '
                             '(a) would have to be applied to it too' % n)
    sysname = re.findall(r'<SystemName>([^<]*)</SystemName>', src_text)
    log('init SystemName %r - LEFT AS EXPORTED (d, STP-847)' % (sysname or [None])[0])
    log('init carries no IsoTimeDuration; derived init is a byte-identical copy')
    return src_text


def selftest():
    ok = True

    def check(label, got, want):
        nonlocal ok
        if got != want:
            ok = False
            print('  MISMATCH %-46s got %r want %r' % (label, got, want))
        else:
            print('  ok       %-46s %r' % (label, got))

    print('to_c2sim_duration:')
    check('PT20M', to_c2sim_duration('PT20M'), 'P00Y00M00DT00H20M00S')
    check('PT30M', to_c2sim_duration('PT30M'), 'P00Y00M00DT00H30M00S')
    check('PT50M', to_c2sim_duration('PT50M'), 'P00Y00M00DT00H50M00S')
    check('PT10M', to_c2sim_duration('PT10M'), 'P00Y00M00DT00H10M00S')
    check('PT0S', to_c2sim_duration('PT0S'), 'P00Y00M00DT00H00M00S')
    check('PT1H30M', to_c2sim_duration('PT1H30M'), 'P00Y00M00DT01H30M00S')
    check('P1DT2H', to_c2sim_duration('P1DT2H'), 'P00Y00M01DT02H00M00S')
    check('idempotent', to_c2sim_duration('P00Y00M00DT00H20M00S'), 'P00Y00M00DT00H20M00S')
    for bad in ('', 'PT20', '20M', 'PT1.5S', 'PT100M', 'P', 'PT', 'nonsense'):
        try:
            to_c2sim_duration(bad)
            ok = False
            print('  MISMATCH %-46s accepted a value it must refuse' % repr(bad))
        except ValueError:
            print('  ok       refused %r' % bad)

    print('apply_code_fix (f):')
    blk = (INDENT + '<UUID>u</UUID>' + EOL + INDENT + '<AffectedEntity>self</AffectedEntity><!--x-->'
           + EOL + INDENT + '<TaskActionCode>ATTACK</TaskActionCode>' + EOL)
    fixed = apply_code_fix(blk, 'ATTACK', 'FOLSPT', 'sup', 'S')
    check('code replaced', '<TaskActionCode>FOLSPT</TaskActionCode>' in fixed
          and 'ATTACK' not in fixed, True)
    check('second AffectedEntity after the first', fixed.index('>self<') < fixed.index('>sup<'), True)
    plain = apply_code_fix(blk.replace('ATTACK', 'ExecutePlanPhase'), 'ExecutePlanPhase',
                           'CNFPSL')
    check('(g) code only, no AffectedEntity added',
          '<TaskActionCode>CNFPSL</TaskActionCode>' in plain
          and plain.count('<AffectedEntity>') == 1, True)
    for label, bad in (('no ATTACK to replace', blk.replace('ATTACK', 'MOVE')),
                       ('already names the unit', blk.replace('self', 'sup'))):
        try:
            apply_code_fix(bad, 'ATTACK', 'FOLSPT', 'sup', 'S')
            ok = False
            print('  MISMATCH %-46s accepted a block it must refuse' % label)
        except AssertionError:
            print('  ok       refused: %s' % label)

    print('apply_reroute (h):')
    init_ok = ('<Entity>' + EOL + '<Latitude>%s</Latitude>' % REROUTE_START[0] + EOL
               + '<Longitude>%s</Longitude>' % REROUTE_START[1] + EOL
               + '<UUID>%s</UUID>' % REROUTE_UNIT + EOL)
    order = ('      <Entity>' + EOL + '<UUID>%s</UUID>' % REROUTE_DEST_GRAPHIC + EOL
             + '      </Entity>' + EOL + '<Task>' + EOL
             + INDENT + '<MapGraphicID>%s</MapGraphicID><!--PassagePoint_48_IBCT_SLOT0 ADDED BY CUT A-->'
             % REROUTE_DEST_GRAPHIC + EOL + '<UUID>%s</UUID>' % REROUTE_TASK + EOL)
    r = apply_reroute(order, lambda m: None, init_ok)
    check('graphic added once', r.count('<UUID>%s</UUID>' % REROUTE_GRAPHIC), 1)
    check('T10 names the reroute BEFORE the destination',
          0 < r.index('<MapGraphicID>%s' % REROUTE_GRAPHIC) < r.index('<MapGraphicID>%s' % REROUTE_DEST_GRAPHIC),
          True)
    check('graphic entity after the destination entity',
          r.index('<UUID>%s</UUID>' % REROUTE_DEST_GRAPHIC) < r.index('<UUID>%s</UUID>' % REROUTE_GRAPHIC), True)
    for label, o, i in (('unit moved in the init', order, init_ok.replace(REROUTE_START[0], '54.0')),
                        ('already applied', r, init_ok),
                        ('T10 lacks the (b) reference', order.replace('ADDED BY CUT A', 'x'), init_ok)):
        try:
            apply_reroute(o, lambda m: None, i)
            ok = False
            print('  MISMATCH %-46s accepted a document it must refuse' % label)
        except AssertionError:
            print('  ok       refused: %s' % label)

    print('apply_t14_waypoint (i):')

    def vtx(lat, lon):
        return '<Latitude>%s</Latitude>' % lat + EOL + '<Longitude>%s</Longitude>' % lon + EOL
    init_i = '<Entity>' + EOL + vtx(*T14WP_START) + '<UUID>%s</UUID>' % T14WP_UNIT + EOL
    order_i = ('      <Entity>' + EOL + '<TaskGraphic>' + EOL
               + '<UUID>%s</UUID>' % T14WP_FOLLOW_GRAPHIC + EOL
               + vtx(*T14WP_START) + vtx(*NUDGE_TO) + '</TaskGraphic>' + EOL
               + '      </Entity>' + EOL + '<Task>' + EOL
               + INDENT + '<MapGraphicID>%s</MapGraphicID><!--FollowAndSupport_48_IBCT_SLOT1-->'
               % T14WP_FOLLOW_GRAPHIC + EOL + '<UUID>%s</UUID>' % T14WP_TASK + EOL)
    ri = apply_t14_waypoint(order_i, lambda m: None, init_i)
    check('(i) graphic added once', ri.count('<UUID>%s</UUID>' % T14WP_GRAPHIC), 1)
    check('(i) T14 names the waypoint BEFORE the FollowAndSupport graphic',
          0 < ri.index('<MapGraphicID>%s' % T14WP_GRAPHIC)
          < ri.index('<MapGraphicID>%s' % T14WP_FOLLOW_GRAPHIC), True)
    check('(i) the added line is [48 IBCT start, waypoint]',
          re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>',
                     ri[ri.index('<UUID>%s</UUID>' % T14WP_GRAPHIC):]),
          [T14WP_START, T14WP_WAYPOINT])
    for label, o, i in (('48 IBCT moved in the init', order_i,
                         init_i.replace(T14WP_START[0], '54.0')),
                        ('already applied', ri, init_i),
                        ('destination not the (e) one', order_i.replace(NUDGE_TO[1], '23.3'),
                         init_i),
                        ('T14 lacks the FollowAndSupport reference',
                         order_i.replace('SLOT1-->', 'x-->'), init_i)):
        try:
            apply_t14_waypoint(o, lambda m: None, i)
            ok = False
            print('  MISMATCH %-46s accepted a document it must refuse' % label)
        except AssertionError:
            print('  ok       refused: %s' % label)

    print('apply_t10_waypoint (j):')
    order_j = apply_reroute(order, lambda m: None, init_ok)
    rj = apply_t10_waypoint(order_j, lambda m: None, init_ok)
    check('(j) graphic added once', rj.count('<UUID>%s</UUID>' % T10WP_GRAPHIC), 1)
    check('(j) T10 names (h), then (j), then the destination',
          0 < rj.index('<MapGraphicID>%s' % REROUTE_GRAPHIC)
          < rj.index('<MapGraphicID>%s' % T10WP_GRAPHIC)
          < rj.index('<MapGraphicID>%s' % REROUTE_DEST_GRAPHIC), True)
    check('(j) graphic entity right after the (h) entity',
          rj.index('<UUID>%s</UUID>' % REROUTE_GRAPHIC) < rj.index('<UUID>%s</UUID>' % T10WP_GRAPHIC),
          True)
    check('(j) the added line is [1-112 IN start, (j) waypoint]',
          re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>',
                     rj[rj.index('<UUID>%s</UUID>' % T10WP_GRAPHIC):]),
          [REROUTE_START, T10WP_WAYPOINT])
    check('(j) chains after (h): (h) waypoint nearer the start',
          _dist_m(REROUTE_START, REROUTE_WAYPOINT) < _dist_m(REROUTE_START, T10WP_WAYPOINT), True)
    check('(j) _dist_m sanity: (h) leg 1 is ~1,453 m',
          abs(_dist_m(REROUTE_START, REROUTE_WAYPOINT) - 1453) < 5, True)
    # the (h) graphic with a moved waypoint (a re-derivation that changed (h) under (j))
    moved_h = order_j.replace('<Latitude>%s</Latitude>' % REROUTE_WAYPOINT[0],
                              '<Latitude>54.0</Latitude>')
    # a (b) reference not directly after (h): some other graphic reference in between
    wedged = order_j.replace(
        '<!--T10_Reroute ADDED BY CUT A (h)-->' + EOL,
        '<!--T10_Reroute ADDED BY CUT A (h)-->' + EOL + INDENT + '<MapGraphicID>x</MapGraphicID>' + EOL)
    for label, o, i in (('1-112 IN moved in the init', order_j,
                         init_ok.replace(REROUTE_START[0], '54.0')),
                        ('already applied', rj, init_ok),
                        ('(h) not applied', order, init_ok),
                        ('(h) waypoint moved', moved_h, init_ok),
                        ('T10 lacks the (b) reference',
                         order_j.replace('SLOT0 ADDED BY CUT A', 'SLOT0 x'), init_ok),
                        ('(h) not immediately before (b)', wedged, init_ok)):
        try:
            apply_t10_waypoint(o, lambda m: None, i)
            ok = False
            print('  MISMATCH %-46s accepted a document it must refuse' % label)
        except AssertionError:
            print('  ok       refused: %s' % label)
    # a (j) waypoint nearer the start than (h)'s would be chained FIRST by the resolver
    saved = T10WP_WAYPOINT
    globals()['T10WP_WAYPOINT'] = ('54.040000', '23.308000')
    try:
        apply_t10_waypoint(order_j, lambda m: None, init_ok)
        ok = False
        print('  MISMATCH %-46s accepted a document it must refuse' % '(j) nearer than (h)')
    except AssertionError:
        print('  ok       refused: (j) waypoint nearer the start than (h)')
    finally:
        globals()['T10WP_WAYPOINT'] = saved

    print('variants (--without):')
    check('no --without = the cut as ruled', parse_without(''), frozenset())
    check('--without i = the run E1 variant', parse_without('i'), frozenset('i'))
    check('--without " i " (whitespace tolerated)', parse_without(' i '), frozenset('i'))
    check('the ruled cut writes IRONSTORM_CUTA_Order.xml',
          os.path.basename(VARIANTS[frozenset()]), 'IRONSTORM_CUTA_Order.xml')
    check('without (i) writes IRONSTORM_CUTA_E1_Order.xml',
          os.path.basename(VARIANTS[frozenset('i')]), 'IRONSTORM_CUTA_E1_Order.xml')
    check('exactly two registered variants', len(VARIANTS), 2)
    # Refused, and for the RIGHT reason: an unknown letter ((k) is on an unmerged branch, and
    # malformed shapes) is 'unknown change letter'; a real change that no registered variant
    # leaves out is 'no registered variant'.
    for bad, why in (('k', 'unmerged branch'), ('z', 'unknown change letter'),
                     ('I', 'unknown change letter'), ('(i)', 'unknown change letter'),
                     ('ij', 'unknown change letter'), ('i,', 'unknown change letter'),
                     (',i', 'unknown change letter'), ('i,k', 'unmerged branch'),
                     ('a', 'no registered variant'), ('e', 'no registered variant'),
                     ('j', 'no registered variant'), ('i,j', 'no registered variant')):
        try:
            parse_without(bad)
            ok = False
            print('  MISMATCH %-46s accepted a --without it must refuse' % repr(bad))
        except ValueError as exc:
            if why in str(exc):
                print('  ok       refused --without %-8r (%s)' % (bad, why))
            else:
                ok = False
                print('  MISMATCH %-46s refused, but not as %r: %s' % (repr(bad), why, exc))
    try:
        derive_order('', lambda m: None, None, frozenset('a'))
        ok = False
        print('  MISMATCH %-46s accepted an unregistered variant' % 'derive_order without (a)')
    except AssertionError as exc:
        if 'no registered variant' in str(exc):
            print('  ok       refused: derive_order without (a) (not a registered variant)')
        else:
            ok = False
            print('  MISMATCH %-46s refused for another reason: %s'
                  % ('derive_order without (a)', exc))

    print('apply_added_graphics with / without (i):')
    init_both = init_ok + init_i          # 1-112 IN and 48 IBCT, one <Entity> each
    order_both = order + order_i          # T10's (b) destination + T14's FollowAndSupport line
    with_i = apply_added_graphics(order_both, lambda m: None, init_both)
    without_i = apply_added_graphics(order_both, lambda m: None, init_both, frozenset('i'))
    check('with (i): the waypoint graphic added once',
          with_i.count('<UUID>%s</UUID>' % T14WP_GRAPHIC), 1)
    check('with (i): T14 names the waypoint, then FollowAndSupport',
          re.findall(r'<MapGraphicID>([^<]*)</MapGraphicID>', with_i[with_i.rindex('<Task>'):]),
          [T14WP_GRAPHIC, T14WP_FOLLOW_GRAPHIC])
    check('without (i): no waypoint graphic anywhere', T14WP_GRAPHIC in without_i, False)
    check('without (i): T14 names ONLY the FollowAndSupport graphic',
          re.findall(r'<MapGraphicID>([^<]*)</MapGraphicID>',
                     without_i[without_i.rindex('<Task>'):]), [T14WP_FOLLOW_GRAPHIC])
    check('without (i): (h) and (j) still applied once each',
          (without_i.count('<UUID>%s</UUID>' % REROUTE_GRAPHIC),
           without_i.count('<UUID>%s</UUID>' % T10WP_GRAPHIC)), (1, 1))
    check('without (i): the (e) destination is still the line end',
          re.findall(r'<Latitude>([^<]*)</Latitude>\s*<Longitude>([^<]*)</Longitude>',
                     without_i[without_i.index('<UUID>%s</UUID>' % T14WP_FOLLOW_GRAPHIC):])[:2],
          [T14WP_START, NUDGE_TO])
    check('without (i) == with (i) minus its two insertions',
          remove_change_i(with_i) == without_i, True)
    for label, o, i in (('(i) graphic present', with_i, init_both),
                        ('48 IBCT moved in the init', order_both,
                         init_both.replace(T14WP_START[0], '54.0')),
                        ('destination not the (e) one', order_both.replace(NUDGE_TO[1], '23.3'),
                         init_both),
                        ('T14 names a second graphic',
                         order_both.replace('SLOT1-->', 'SLOT1-->' + EOL + INDENT
                                            + '<MapGraphicID>x</MapGraphicID>'), init_both)):
        try:
            assert_t14_original_line(o, i)
            ok = False
            print('  MISMATCH %-46s accepted a document it must refuse' % label)
        except AssertionError:
            print('  ok       refused (original line): %s' % label)
    for label, doc in (('remove (i) where it is absent', without_i),
                       ('remove (i) where it occurs twice', with_i + t14_waypoint_ref())):
        try:
            remove_change_i(doc)
            ok = False
            print('  MISMATCH %-46s accepted a document it must refuse' % label)
        except AssertionError:
            print('  ok       refused: %s' % label)

    print('the FULL variant (--variant full):')
    check('EXPORT_TASKS lists 23 distinct tasks', len(set(u for u, _l in EXPORT_TASKS)), 23)
    check('KEEP_FULL = 22 tasks, T12 the one dropped',
          sorted(set(dict(EXPORT_TASKS).values()) - set(KEEP_FULL.values())), ['T12'])
    check('KEEP_FULL holds every cut-A task under the same label',
          all(KEEP_FULL.get(u) == lab for u, lab in KEEP.items()), True)
    check('CODE_FIX_FULL = CODE_FIX + T03 only',
          sorted(KEEP_FULL[u] for u in set(CODE_FIX_FULL) - set(CODE_FIX)), ['T03'])
    check('CODE_FIX_FULL keeps every cut-A fix as is',
          all(CODE_FIX_FULL[u] == fx for u, fx in CODE_FIX.items()), True)
    blk_a = '  <Task>' + EOL + '<UUID>a</UUID>' + EOL + '  </Task>' + EOL
    blk_b = '  <Task>' + EOL + '<UUID>b</UUID>' + EOL + '  </Task>' + EOL
    check('strip_tasks drops every task block',
          strip_tasks('<x>' + EOL + blk_a + blk_b + '</x>'), '<x>' + EOL + '</x>')
    for label, full_doc in (('differs outside the task blocks', '<y>' + EOL + blk_a + '</x>'),
                            ('lacks a cut-A task block', '<x>' + EOL + blk_b + '</x>')):
        try:
            assert_full_extends_cuta(full_doc, '<x>' + EOL + blk_a + '</x>')
            ok = False
            print('  MISMATCH %-46s accepted a document it must refuse' % label)
        except AssertionError:
            print('  ok       refused (full extends cut A): %s' % label)
    # a keep-set that drops a kept task's predecessor must be refused, not derived
    chain = ('<Task>' + EOL + '<UUID>p</UUID>' + EOL + '</Task>' + EOL
             + '<Task>' + EOL + '<TemporalAssociationWithAction>p</TemporalAssociationWithAction>'
             + EOL + '<UUID>s</UUID>' + EOL + '</Task>' + EOL)
    try:
        derive_order(chain, lambda m: None, None, frozenset(), {'s': 'S'}, {})
        ok = False
        print('  MISMATCH %-46s accepted a keep-set it must refuse' % 'successor without predecessor')
    except AssertionError as exc:
        if 'depends on dropped task' in str(exc):
            print('  ok       refused: a kept successor whose predecessor is dropped')
        else:
            ok = False
            print('  MISMATCH %-46s refused for another reason: %s'
                  % ('successor without predecessor', exc))

    print('gate (proven on a DIRTY control first, per the ASCII rule):')
    good = ('<?xml version="1.0" encoding="utf-8"?>\r\n<MessageBody xmlns="%s">\r\n'
            '  <A>x</A>\r\n</MessageBody>' % NS)
    for label, sample, must_fire in [
            ('clean sample', good, False),
            # chr(), not a literal: THIS FILE IS ASCII-ONLY and must stay so,
            # while the control it builds has to be genuinely dirty or the gate
            # would pass vacuously.
            ('non-ASCII em dash',
             good.replace('<A>x', '<A>' + chr(0x2014)), True),
            ('NBSP', good.replace('<A>x', '<A>' + chr(0x00A0)), True),
            ('bare LF', good.replace('\r\n', '\n', 1), True),
            ('stray CR', good.replace('<A>', '\r<A>'), True),
            ('comment with a tag token', good.replace('  <A>', '  <!--<Task-->\r\n  <A>'), True),
            ('comment before the root', '<!--<x-->\r\n' + good, True)]:
        problems = []
        gate(sample, label, problems)
        fired = bool(problems)
        if fired != must_fire:
            ok = False
            print('  MISMATCH %-46s fired=%s want=%s %s'
                  % (label, fired, must_fire, problems[:1]))
        else:
            print('  ok       %-46s fired=%s' % (label, fired))

    print('SELFTEST %s' % ('PASSED' if ok else 'FAILED'))
    return 0 if ok else 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--check', action='store_true',
                    help='derive and verify, but write nothing; non-zero if the files '
                         'on disk differ from what the script would write')
    ap.add_argument('--selftest', action='store_true',
                    help='run the pure-function tests and exit')
    ap.add_argument('--without', metavar='LETTERS', default='',
                    help="write a REGISTERED variant that leaves change(s) out. Only 'i' exists: "
                         "run E1, T14 on its original line -> data/IRONSTORM_CUTA_E1_Order.xml. "
                         "Any other letter is refused (exit 4). --check always verifies every "
                         "variant, whatever this says.")
    ap.add_argument('--variant', choices=('cuta', 'full'), default='cuta',
                    help="'cuta' (default) writes the cut-A pair (or the --without variant); 'full' "
                         "writes data/IRONSTORM_FULL_Order.xml - every task but T12, the same "
                         "changes (data/IRONSTORM_FULL_CHANGES.md). --check verifies both, whatever "
                         "this says.")
    args = ap.parse_args(argv)
    if args.selftest:
        return selftest()
    try:
        without = parse_without(args.without)
    except ValueError as exc:
        print('REFUSED --without %r: %s' % (args.without, exc))
        return 4
    if args.variant == 'full' and without:
        print('REFUSED --without %r with --variant full: the full variant leaves no change out'
              % args.without)
        return 4

    def log(msg):
        print(msg)

    src_order = read(SRC_ORDER)
    src_init = read(SRC_INIT)
    log('INPUT  %s  sha256 %s' % (os.path.basename(SRC_INIT), sha(src_init)))
    log('INPUT  %s  sha256 %s' % (os.path.basename(SRC_ORDER), sha(src_order)))
    # EVERY registered variant is derived and gated on every run, whatever is written, so the
    # variants cannot drift apart; the ruled cut first.
    orders = {}
    for v in sorted(VARIANTS, key=len):
        log('')
        log('=== ORDER VARIANT: %s -> %s ===' % (variant_label(v), os.path.basename(VARIANTS[v])))
        orders[v] = derive_order(src_order, log, src_init, v)
    log('')
    log('=== ORDER VARIANT: FULL (every task but T12, all changes) -> %s ==='
        % os.path.basename(OUT_ORDER_FULL))
    full_order = derive_order_full(src_order, log, src_init)
    log('')
    out_init = derive_init(src_init, log)
    log('')

    problems = []
    for v in orders:
        gate(orders[v], 'derived order (%s)' % variant_label(v), problems)
    gate(full_order, 'derived order (FULL)', problems)
    gate(out_init, 'derived init', problems)
    if problems:
        for p in problems:
            print('GATE FAILURE: %s' % p)
        return 2
    log('gates: ASCII, CRLF, STP-830 comment scan, well-formedness, root, namespace, '
        'duration pattern - ALL PASS (%d order variant(s) + the init)' % (len(orders) + 1))

    # ONE CHANGE APART: the without-(i) order must be the full order minus (i)'s two insertions
    # and nothing else - what lets a run on it claim T14's route as its one variable.
    try:
        one_apart = remove_change_i(orders[frozenset()]) == orders[frozenset('i')]
    except AssertionError as exc:
        print('CHECK FAILURE: the full order does not carry (i) as derived: %s' % exc)
        return 3
    if not one_apart:
        print('CHECK FAILURE: the without-(i) order is NOT the full order minus (i) - they '
              'differ elsewhere too')
        return 3
    log('variants: without (i) == as ruled minus (i)\'s graphic entity and MapGraphicID line - '
        'ONE change apart')
    try:
        assert_full_extends_cuta(full_order, orders[frozenset()])
    except AssertionError as exc:
        print('CHECK FAILURE: %s' % exc)
        return 3
    log('variants: FULL == cut A plus %d more task blocks; outside the task blocks byte-identical, '
        'and each cut-A task block verbatim' % (len(KEEP_FULL) - len(KEEP)))

    if args.check:
        targets = ([(OUT_INIT, out_init)] + [(VARIANTS[v], orders[v]) for v in orders]
                   + [(OUT_ORDER_FULL, full_order)])
        if without or args.variant != 'cuta':
            log('(--check verifies every variant; --without / --variant do not narrow it)')
    elif args.variant == 'full':
        # no init is written: the full variant uses the export's init, unchanged (derive_init)
        targets = [(OUT_ORDER_FULL, full_order)]
    else:
        targets = [(OUT_INIT, out_init), (VARIANTS[without], orders[without])]
    for path, text in targets:
        name = os.path.basename(path)
        if args.check:
            if not os.path.exists(path):
                print('CHECK FAILURE: %s does not exist' % name)
                return 3
            if read(path) != text:
                print('CHECK FAILURE: %s on disk differs from the derivation' % name)
                return 3
            log('CHECK  %s  matches  sha256 %s' % (name, sha(text)))
        else:
            write(path, text)
            log('OUTPUT %s  sha256 %s  (%d bytes)'
                % (name, sha(text), len(text.encode('utf-8'))))
    if not args.check:
        for v in orders:
            if v != without or args.variant == 'full':
                log('NOT WRITTEN %s (%s; derived and gated only - %s writes it)'
                    % (os.path.basename(VARIANTS[v]), variant_label(v),
                       '--without ' + ','.join(sorted(v)) if v else 'a run with no --without'))
        if args.variant != 'full':
            log('NOT WRITTEN %s (FULL; derived and gated only - --variant full writes it)'
                % os.path.basename(OUT_ORDER_FULL))
    return 0


if __name__ == '__main__':
    sys.exit(main())
