#!/usr/bin/env python3
"""Derive the IRON STORM "CUT A" demo pair from the user's authoritative STP export.

WHY THIS IS A SCRIPT AND NOT A HAND EDIT
    The export is regenerated by STP whenever the plan changes. Every change this cut
    needs is mechanical, so it is expressed here once and re-applied on demand: re-run
    the script after a re-export and the derived pair is rebuilt, or the script FAILS
    LOUDLY because an assumption it depends on (a uuid, a task, an element order) no
    longer holds. It never edits in place and never guesses.

INPUTS  (byte-exact, never modified)
    data/STP-IRON-STORM-SYNTHETIC_Initialization.xml
    data/STP-IRON-STORM-SYNTHETIC_Order.xml
OUTPUTS (tracked)
    data/IRONSTORM_CUTA_Initialization.xml
    data/IRONSTORM_CUTA_Order.xml

THE COMPLETE CHANGE LIST - nothing else is touched. Exactly ONE coordinate pair moves
(change (e), a user ruling); no unit is renamed, no TaskActionCode is altered, no graphic
is added or removed, no comment is rewritten, and the root element + namespace + CRLF line
endings are preserved byte for byte. See data/IRONSTORM_CUTA_CHANGES.md for the rationale
and the consequences.

  (a) DURATION FORMAT (connector bug STP-848). Every IsoTimeDuration value is rewritten
      from the canonical-ISO short form the export writes ("PT20M") to the C2SIM 1.1
      pattern form ("P00Y00M00DT00H20M00S"). The schema's IsoTimeDurationBaseType is an
      xs:string restricted by
        [P]{1}[0-9]{2}[Y]{1}[0-9]{2}[M]{1}[0-9]{2}[D]{1}T{1}[0-9]{2}[H]{1}[0-9]{2}[M]{1}[0-9]{2}[S]{1}
      (C2SIM_SMX_LOX_CWIX2024.xsd:17-24) - every field present, two digits wide. The
      short form is NOT valid C2SIM 1.1, and OrderParser.FindTotalIsoMs refuses it
      (returns -1 -> DurationMs 0), which is what leaves the export's HoldInPlace tasks
      MALFORMED and their STREND successors waiting out the gate. This rewrite changes
      no VALUE - only the spelling. 46 values in the order; the init carries none.

  (b) TWO MapGraphicID REFERENCES ADDED, to existing graphics the order ALREADY carries.
      No new geometry is authored.
        T02 (28ID, ATTACK)     -> c8cde9b6-17f7-f253-800e-4de0cae84db3
                                  PassagePoint_28ID_SLOT0
        T10 (1-112 IN, CRESRV) -> cc23071f-aa60-9f52-884c-11505051cc99
                                  PassagePoint_48_IBCT_SLOT0
      Both tasks carry NO geometry at all in the export, so both execute in place and
      the cut has nothing to watch. MapGraphicID is inserted immediately before Name,
      which is where the schema's ActionGroup sequence puts it.

  (c) THE ORDER IS REDUCED to the CUT-3 task set plus the predecessors its temporal
      chains need. KEPT: T01 -> T02 (28ID), T10 (1-112 IN, a chain root), T13 -> T14
      (48 IBCT). DROPPED: the other 18 tasks. Chain integrity is ASSERTED, not assumed:
      every kept task's ActionTemporalRelationship/TemporalAssociationWithAction must
      name a task that is also kept, or the script fails.

  (d) SystemName IS LEFT AS EXPORTED ("Not Set" - connector bug STP-847). The run passes
      --client-id "Not Set" so that the interface's own ClientId filter matches. This is
      deliberately NOT papered over in the data: the defect belongs on the producer side
      and the data file is the evidence.

  (e) T14's DESTINATION IS MOVED 799 m DUE WEST, out of a lake - the ONE coordinate this
      script changes. USER RULING 2026-09-21 ("as recommended"); STP will not re-author it.
        BEFORE  54.04034819271516 / 23.336444730300467
        AFTER   54.040348        / 23.324206
      The authored leg crosses CLCplus class 100 (preset="Water") for 1,565 m of its
      2,757 m, and deep-water is acceleration-factor 0.000000, so the unit would stop dead
      with the task reported TaskRunning for ever. Applied to the graphic the interface
      actually drives AND to T14's mirrored embedded Location - see apply_water_nudge.
      NO OTHER COORDINATE MOVES.

USAGE
    python tools/scenario/derive_ironstorm_cuta.py                 # write the pair
    python tools/scenario/derive_ironstorm_cuta.py --check         # verify, write nothing
    python tools/scenario/derive_ironstorm_cuta.py --selftest      # pure-function tests

The script is deterministic: the same inputs always produce byte-identical outputs, and
it prints the SHA-256 of every input and output so a derivation can be audited later.
"""

import argparse
import hashlib
import os
import re
import sys
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

SRC_INIT = os.path.join(REPO, 'data', 'STP-IRON-STORM-SYNTHETIC_Initialization.xml')
SRC_ORDER = os.path.join(REPO, 'data', 'STP-IRON-STORM-SYNTHETIC_Order.xml')
OUT_INIT = os.path.join(REPO, 'data', 'IRONSTORM_CUTA_Initialization.xml')
OUT_ORDER = os.path.join(REPO, 'data', 'IRONSTORM_CUTA_Order.xml')

NS = 'http://www.sisostds.org/schemas/C2SIM/1.1'
Q = '{%s}' % NS

# ---------------------------------------------------------------------------
# (c) THE CUT. uuid -> the label this project uses for the task in its records.
# The order is the order the tasks appear in the export, which is the order they are
# written out in; nothing is resequenced.
# ---------------------------------------------------------------------------
KEEP = {
    'f7b52ba4-c889-4a28-9f3a-e9715cd8a65f': 'T01',  # 28ID     ExecutePlanPhase (root)
    '696fbb33-3dce-4854-8935-55fed398c247': 'T02',  # 28ID     ATTACK, STREND on T01
    '9aab7fe6-c7fb-4e74-b586-e11a00fc3eb9': 'T10',  # 1-112 IN CRESRV (root)
    '37677c40-c595-4b4c-9039-e9865abb4eb3': 'T13',  # 48 IBCT  ExecutePlanPhase (root)
    '1075b583-a7b8-45e5-b22b-d09988c9443e': 'T14',  # 48 IBCT  ATTACK, STREND on T13
}

# ---------------------------------------------------------------------------
# (b) THE TWO ADDED REFERENCES. task uuid -> (graphic uuid, the graphic's Name in the
# export). The Name is carried here so the script can VERIFY it rather than trust it.
# ---------------------------------------------------------------------------
ADD_GRAPHIC = {
    '696fbb33-3dce-4854-8935-55fed398c247': (
        'c8cde9b6-17f7-f253-800e-4de0cae84db3',
        'PassagePoint_28ID_SLOT0__FRIENDLY_PASSAGE_POINT_PassagePoint_28',
        'PassagePoint_28ID_SLOT0'),
    '9aab7fe6-c7fb-4e74-b586-e11a00fc3eb9': (
        'cc23071f-aa60-9f52-884c-11505051cc99',
        'PassagePoint_48_IBCT_SLOT0__FRIENDLY_PASSAGE_POINT_PassagePoint',
        'PassagePoint_48_IBCT_SLOT0'),
}

EOL = '\r\n'
INDENT = ' ' * 10          # the export's indent for ManeuverWarfareTask children

# ---------------------------------------------------------------------------
# (e) THE WATER NUDGE on T14's destination. USER RULING 2026-09-21 ("as recommended"):
# apply the 800 m-west destination nudge in the DERIVED file; STP will not re-author it.
#
# WHY. The authored leg 48 IBCT -> 54.04034819271516/23.336444730300467 crosses OPEN
# WATER: CLCplus (dataset 59, level 14) class 100, preset="Water", from 752 m to 2,346 m
# along a 2,757 m leg - 72 of 276 samples at a 10 m stride. `deep-water` is
# acceleration-factor 0.000000 in ground-tracked.sysdef, so a ground vehicle driven onto
# it STOPS and the vendor reports TaskRunning for ever. The lateral route shift cannot
# save it: the shift only fires on a leg FLAGGED for grade, and this leg's ratio is 0.10.
#
#   BEFORE  54.04034819271516  / 23.336444730300467
#   AFTER   54.040348          / 23.324206            (799 m due west)
#
# Measured dry at FOUR strides after the move - 25 m, 10 m, 5 m and 2 m (1,213 samples at
# 2 m, zero water) - because the original 25 m stride is coarse enough to step over a
# narrow inlet, and a dry verdict that depends on the stride is not a verdict.
#
# WHICH COPY IS AUTHORITATIVE. The interface drives the MAPGRAPHIC, not the embedded
# Location (TaskGeometryResolver returns GeometrySource.MapGraphic as soon as a graphic
# resolves). T14 names ONE graphic, 7351f662 FollowAndSupport_48_IBCT_SLOT1, a TaskGraphic
# with two vertices; under main's role-based resolver that is a LINE, its first vertex IS
# 48 IBCT's own position and is dropped at OriginCoincidenceMeters, and the SECOND vertex
# is the destination. So the graphic's second vertex is what had to move. T14's embedded
# Location carries the same pair and is moved WITH it so the two cannot disagree - the
# coordinate appears exactly twice in the derived order and both are rewritten.
# ---------------------------------------------------------------------------
NUDGE_FROM = ('54.04034819271516', '23.336444730300467')
NUDGE_TO = ('54.040348', '23.324206')
NUDGE_EXPECTED_SITES = 2       # the graphic's 2nd vertex + T14's embedded Location
NUDGE_GRAPHIC = '7351f662-f857-e05a-b533-f9a46e0fb095'
NUDGE_TASK = '1075b583-a7b8-45e5-b22b-d09988c9443e'


# ---------------------------------------------------------------------------
# (a) the duration rewrite - a pure function, self-tested below
# ---------------------------------------------------------------------------
C2SIM_DURATION = re.compile(
    r'^P[0-9]{2}Y[0-9]{2}M[0-9]{2}DT[0-9]{2}H[0-9]{2}M[0-9]{2}S$')

# canonical ISO-8601: PnYnMnDTnHnMnS with any field omitted. Fractions are NOT accepted -
# the C2SIM pattern has no room for them, so silently truncating one would change a value.
ISO_8601 = re.compile(
    r'^P(?:([0-9]+)Y)?(?:([0-9]+)M)?(?:([0-9]+)D)?'
    r'(?:T(?:([0-9]+)H)?(?:([0-9]+)M)?(?:([0-9]+)S)?)?$')


def to_c2sim_duration(value):
    """Rewrite an ISO-8601 duration into the C2SIM 1.1 pattern form.

    Already-conforming values are returned unchanged. Anything that cannot be read as a
    whole-number ISO-8601 duration, or whose fields do not fit two digits, raises - the
    point of this script is that a format it does not understand STOPS it, rather than
    being passed through to produce a plausible wrong time.
    """
    v = (value or '').strip()
    if C2SIM_DURATION.match(v):
        return v
    m = ISO_8601.match(v)
    if not m or v in ('P', 'PT'):
        raise ValueError('not an ISO-8601 duration this script can rewrite: %r' % value)
    y, mo, d, h, mi, s = (int(g) if g else 0 for g in m.groups())
    for label, n in (('years', y), ('months', mo), ('days', d),
                     ('hours', h), ('minutes', mi), ('seconds', s)):
        if n > 99:
            raise ValueError('%s=%d does not fit the C2SIM two-digit field in %r'
                             % (label, n, value))
    return 'P%02dY%02dM%02dDT%02dH%02dM%02dS' % (y, mo, d, h, mi, s)


def rewrite_durations(text):
    """Rewrite every IsoTimeDuration element value in place. Returns (text, changes)."""
    changes = []

    def sub(m):
        old = m.group(1)
        new = to_c2sim_duration(old)
        if new != old:
            changes.append((old, new))
        return '<IsoTimeDuration>%s</IsoTimeDuration>' % new

    out = re.sub(r'<IsoTimeDuration>([^<]*)</IsoTimeDuration>', sub, text)
    return out, changes


# ---------------------------------------------------------------------------
# task blocks
# ---------------------------------------------------------------------------
TASK_BLOCK = re.compile(r'[ \t]*<Task>\r\n.*?[ \t]*</Task>\r\n', re.S)


def task_uuid(block):
    m = re.search(r'<UUID>([^<]+)</UUID>', block)
    return m.group(1).strip() if m else None


def apply_water_nudge(text, log):
    """(e) Move T14's destination 799 m due west, out of the lake. Pure text surgery on the
    ONE coordinate pair, asserted to appear exactly twice - the graphic vertex the
    interface drives and T14's embedded Location that mirrors it.

    Everything is checked rather than assumed: the pair must appear exactly
    NUDGE_EXPECTED_SITES times, the target longitude must not already be present, and
    afterwards BOTH the graphic block and the task block must carry the new value. Any of
    those failing raises, because a half-applied nudge would leave the driven route and
    the embedded route disagreeing - which is precisely the class of defect this script
    exists to make impossible.
    """
    old_lat, old_lon = NUDGE_FROM
    new_lat, new_lon = NUDGE_TO
    pair_old = ('<Latitude>%s</Latitude>' % old_lat, '<Longitude>%s</Longitude>' % old_lon)
    n_lat = text.count(pair_old[0])
    n_lon = text.count(pair_old[1])
    if n_lat != NUDGE_EXPECTED_SITES or n_lon != NUDGE_EXPECTED_SITES:
        raise AssertionError('(e) expected the destination pair %s/%s exactly %d time(s); '
                             'found lat x%d, lon x%d - the export has changed shape'
                             % (old_lat, old_lon, NUDGE_EXPECTED_SITES, n_lat, n_lon))
    if ('<Longitude>%s</Longitude>' % new_lon) in text:
        raise AssertionError('(e) the target longitude %s is already present' % new_lon)

    text = text.replace(pair_old[0], '<Latitude>%s</Latitude>' % new_lat)
    text = text.replace(pair_old[1], '<Longitude>%s</Longitude>' % new_lon)

    # Both sites must really have moved: the graphic the interface drives, and the task.
    for label, uuid in (('graphic %s' % NUDGE_GRAPHIC[:8], NUDGE_GRAPHIC),
                        ('task %s (T14)' % NUDGE_TASK[:8], NUDGE_TASK)):
        at = text.find('<UUID>%s</UUID>' % uuid)
        if at < 0:
            raise AssertionError('(e) %s vanished from the derived order' % label)
        start = max(0, at - 4000)
        window = text[start:at + 4000]
        if ('<Longitude>%s</Longitude>' % new_lon) not in window:
            raise AssertionError('(e) %s does not carry the nudged longitude' % label)
    log('  (e) T14 destination %s,%s -> %s,%s  (799 m due west, out of the lake; '
        'USER RULING 2026-09-21) - %d site(s): the driven MapGraphic vertex and the '
        'mirrored embedded Location'
        % (old_lat, old_lon, new_lat, new_lon, NUDGE_EXPECTED_SITES))
    return text


def insert_map_graphic(block, graphic_uuid, short_name):
    """Insert one MapGraphicID immediately before Name - where the schema's ActionGroup
    sequence puts it (ActionTemporalRelationship, Location*, MapGraphicID*, Name, UUID).
    The annotation comment matches the style the export uses on every other
    MapGraphicID, and carries no '<word' token (the C2SIM SDK's DetermineProtocol reads
    the first '<'+letter ANYWHERE in the text, comments included - STP-830)."""
    needle = INDENT + '<Name>'
    at = block.find(needle)
    if at < 0:
        raise AssertionError('no <Name> at the expected indent in task block')
    line = ('%s<MapGraphicID>%s</MapGraphicID><!--%s ADDED BY CUT A-->%s'
            % (INDENT, graphic_uuid, short_name, EOL))
    return block[:at] + line + block[at:]


# ---------------------------------------------------------------------------
# gates
# ---------------------------------------------------------------------------
def gate(text, label, problems):
    """Every hazard this project has actually been bitten by, checked on the OUTPUT."""
    # ASCII only (control characters included - a stray VT/BEL is not printable ASCII)
    bad = [(i, c) for i, c in enumerate(text)
           if not (c in '\t\r\n' or ' ' <= c <= '~')]
    if bad:
        problems.append('%s: %d non-ASCII/control byte(s), first at offset %d (0x%02X)'
                        % (label, len(bad), bad[0][0], ord(bad[0][1])))
    # CRLF class preserved: no lone LF, no lone CR
    if re.search(r'(?<!\r)\n', text):
        problems.append('%s: a bare LF (the export is 100%% CRLF)' % label)
    if re.search(r'\r(?!\n)', text):
        problems.append('%s: a stray CR' % label)
    # STP-830: the SDK takes the first '<'+letter in the TEXT - comments included - as the
    # message root. Nothing may precede MessageBody, and no comment may hold such a token.
    first = re.search(r'<[A-Za-z_]', text)
    if not first or not text.startswith('<?xml', 0) or text[first.start():first.start() + 12] != '<MessageBody':
        problems.append('%s: the first "<word" token is not <MessageBody' % label)
    for c in re.findall(r'<!--(.*?)-->', text, re.S):
        if re.search(r'<[A-Za-z_]', c):
            problems.append('%s: an XML comment carries a "<word" token: %r' % (label, c[:60]))
    # well-formed, right root, right namespace
    try:
        root = ET.fromstring(text)
    except Exception as exc:                                   # noqa: BLE001
        problems.append('%s: not well-formed XML: %s' % (label, exc))
        return
    if root.tag != Q + 'MessageBody':
        problems.append('%s: root is %s, expected %sMessageBody' % (label, root.tag, Q))
    for v in re.findall(r'<IsoTimeDuration>([^<]*)</IsoTimeDuration>', text):
        if not C2SIM_DURATION.match(v):
            problems.append('%s: IsoTimeDuration %r still violates the C2SIM pattern'
                            % (label, v))


def sha(data):
    return hashlib.sha256(data if isinstance(data, bytes)
                          else data.encode('utf-8')).hexdigest()


def read(path):
    with open(path, 'r', encoding='utf-8', newline='') as fh:
        return fh.read()


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='') as fh:
        fh.write(text)


# ---------------------------------------------------------------------------
def derive_order(src_text, log):
    """Apply (a), (b) and (c) to the order text. Returns the derived text."""
    blocks = TASK_BLOCK.findall(src_text)
    log('order carries %d <Task> blocks' % len(blocks))
    if len(blocks) != src_text.count('<Task>'):
        raise AssertionError('the Task-block scanner missed %d of %d blocks'
                             % (src_text.count('<Task>') - len(blocks),
                                src_text.count('<Task>')))

    by_uuid = {}
    for b in blocks:
        u = task_uuid(b)
        if u is None:
            raise AssertionError('a <Task> block carries no <UUID>')
        if u in by_uuid:
            raise AssertionError('duplicate task uuid %s' % u)
        by_uuid[u] = b

    missing = sorted(set(KEEP) - set(by_uuid))
    if missing:
        raise AssertionError('the export no longer carries kept task(s): %s'
                             % ', '.join(missing))

    # (c) chain integrity: every kept task's predecessor must also be kept.
    for u in KEEP:
        m = re.search(r'<TemporalAssociationWithAction>([^<]+)<', by_uuid[u])
        pred = m.group(1).strip() if m else None
        if pred and pred not in KEEP:
            raise AssertionError('kept task %s (%s) depends on dropped task %s'
                                 % (KEEP[u], u, pred))
        log('  keep %s %s  predecessor=%s' % (KEEP[u], u, KEEP.get(pred, '-')))

    # (b) verify each added graphic EXISTS in the order, is a Point, and carries the Name
    # this script expects; then verify the task does not already reference it.
    for task_u, (g_uuid, g_name, _short) in ADD_GRAPHIC.items():
        at = src_text.find('<UUID>%s</UUID>' % g_uuid)
        if at < 0:
            raise AssertionError('graphic %s is not in the order' % g_uuid)
        start = src_text.rfind('<TacticalGraphic>', 0, at)
        end = src_text.find('</TacticalGraphic>', at)
        blk = src_text[start:end]
        if '<Point>' not in blk:
            raise AssertionError('graphic %s is not a <Point>' % g_uuid)
        nm = re.search(r'<Name>([^<]*)</Name>', blk)
        if not nm or nm.group(1).strip() != g_name:
            raise AssertionError('graphic %s Name is %r, expected %r'
                                 % (g_uuid, nm.group(1) if nm else None, g_name))
        if g_uuid in by_uuid[task_u]:
            raise AssertionError('task %s already references %s' % (KEEP[task_u], g_uuid))
        lat = re.search(r'<Latitude>([^<]*)</Latitude>', blk)
        lon = re.search(r'<Longitude>([^<]*)</Longitude>', blk)
        log('  add  %s -> %s  %s  @ %s, %s'
            % (KEEP[task_u], g_uuid, g_name[:34], lat.group(1), lon.group(1)))

    # Build the derived text: walk the ORIGINAL string, copying everything, replacing the
    # kept task blocks with their edited form and deleting the rest. Working on the raw
    # string (never on a re-serialized tree) is what keeps every untouched byte identical.
    out = []
    pos = 0
    kept = dropped = 0
    for m in TASK_BLOCK.finditer(src_text):
        out.append(src_text[pos:m.start()])
        pos = m.end()
        block = m.group(0)
        u = task_uuid(block)
        if u not in KEEP:
            dropped += 1
            continue
        if u in ADD_GRAPHIC:
            g_uuid, _g_name, short = ADD_GRAPHIC[u]
            block = insert_map_graphic(block, g_uuid, short)
        out.append(block)
        kept += 1
    out.append(src_text[pos:])
    text = ''.join(out)
    log('kept %d task(s), dropped %d' % (kept, dropped))
    if kept != len(KEEP):
        raise AssertionError('kept %d tasks, expected %d' % (kept, len(KEEP)))

    # (e) the water nudge, on the assembled document so the site count is the DERIVED
    # file's and not the export's.
    text = apply_water_nudge(text, log)

    # (a) last, so it covers the whole derived document including nothing new (the
    # inserted lines carry no duration).
    text, changes = rewrite_durations(text)
    log('rewrote %d IsoTimeDuration value(s)' % len(changes))
    seen = {}
    for old, new in changes:
        seen.setdefault((old, new), 0)
        seen[(old, new)] += 1
    for (old, new), n in sorted(seen.items()):
        log('  %-6s -> %-22s x%d' % (old, new, n))
    return text


def derive_init(src_text, log):
    """The init needs NO change: it carries no IsoTimeDuration (verified here, not
    assumed), no task, and its SystemName is left exactly as exported - (d). The derived
    file is therefore a byte-identical copy under the cut's own name."""
    n = len(re.findall(r'<IsoTimeDuration>', src_text))
    if n:
        raise AssertionError('the init now carries %d IsoTimeDuration value(s); change '
                             '(a) would have to be applied to it too' % n)
    sysname = re.findall(r'<SystemName>([^<]*)</SystemName>', src_text)
    log('init SystemName %r - LEFT AS EXPORTED (d, STP-847)' % (sysname or [None])[0])
    log('init carries no IsoTimeDuration; derived init is a byte-identical copy')
    return src_text


def selftest():
    ok = True

    def check(label, got, want):
        nonlocal ok
        if got != want:
            ok = False
            print('  MISMATCH %-46s got %r want %r' % (label, got, want))
        else:
            print('  ok       %-46s %r' % (label, got))

    print('to_c2sim_duration:')
    check('PT20M', to_c2sim_duration('PT20M'), 'P00Y00M00DT00H20M00S')
    check('PT30M', to_c2sim_duration('PT30M'), 'P00Y00M00DT00H30M00S')
    check('PT50M', to_c2sim_duration('PT50M'), 'P00Y00M00DT00H50M00S')
    check('PT10M', to_c2sim_duration('PT10M'), 'P00Y00M00DT00H10M00S')
    check('PT0S', to_c2sim_duration('PT0S'), 'P00Y00M00DT00H00M00S')
    check('PT1H30M', to_c2sim_duration('PT1H30M'), 'P00Y00M00DT01H30M00S')
    check('P1DT2H', to_c2sim_duration('P1DT2H'), 'P00Y00M01DT02H00M00S')
    check('idempotent', to_c2sim_duration('P00Y00M00DT00H20M00S'), 'P00Y00M00DT00H20M00S')
    for bad in ('', 'PT20', '20M', 'PT1.5S', 'PT100M', 'P', 'PT', 'nonsense'):
        try:
            to_c2sim_duration(bad)
            ok = False
            print('  MISMATCH %-46s accepted a value it must refuse' % repr(bad))
        except ValueError:
            print('  ok       refused %r' % bad)

    print('gate (proven on a DIRTY control first, per the ASCII rule):')
    good = ('<?xml version="1.0" encoding="utf-8"?>\r\n<MessageBody xmlns="%s">\r\n'
            '  <A>x</A>\r\n</MessageBody>' % NS)
    for label, sample, must_fire in [
            ('clean sample', good, False),
            # chr(), not a literal: THIS FILE IS ASCII-ONLY and must stay so,
            # while the control it builds has to be genuinely dirty or the gate
            # would pass vacuously.
            ('non-ASCII em dash',
             good.replace('<A>x', '<A>' + chr(0x2014)), True),
            ('NBSP', good.replace('<A>x', '<A>' + chr(0x00A0)), True),
            ('bare LF', good.replace('\r\n', '\n', 1), True),
            ('stray CR', good.replace('<A>', '\r<A>'), True),
            ('comment with a tag token', good.replace('  <A>', '  <!--<Task-->\r\n  <A>'), True),
            ('comment before the root', '<!--<x-->\r\n' + good, True)]:
        problems = []
        gate(sample, label, problems)
        fired = bool(problems)
        if fired != must_fire:
            ok = False
            print('  MISMATCH %-46s fired=%s want=%s %s'
                  % (label, fired, must_fire, problems[:1]))
        else:
            print('  ok       %-46s fired=%s' % (label, fired))

    print('SELFTEST %s' % ('PASSED' if ok else 'FAILED'))
    return 0 if ok else 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--check', action='store_true',
                    help='derive and verify, but write nothing; non-zero if the files '
                         'on disk differ from what the script would write')
    ap.add_argument('--selftest', action='store_true',
                    help='run the pure-function tests and exit')
    args = ap.parse_args(argv)
    if args.selftest:
        return selftest()

    def log(msg):
        print(msg)

    src_order = read(SRC_ORDER)
    src_init = read(SRC_INIT)
    log('INPUT  %s  sha256 %s' % (os.path.basename(SRC_INIT), sha(src_init)))
    log('INPUT  %s  sha256 %s' % (os.path.basename(SRC_ORDER), sha(src_order)))
    log('')
    out_order = derive_order(src_order, log)
    out_init = derive_init(src_init, log)
    log('')

    problems = []
    gate(out_order, 'derived order', problems)
    gate(out_init, 'derived init', problems)
    if problems:
        for p in problems:
            print('GATE FAILURE: %s' % p)
        return 2
    log('gates: ASCII, CRLF, STP-830 comment scan, well-formedness, root, namespace, '
        'duration pattern - ALL PASS')

    for path, text in ((OUT_INIT, out_init), (OUT_ORDER, out_order)):
        name = os.path.basename(path)
        if args.check:
            if not os.path.exists(path):
                print('CHECK FAILURE: %s does not exist' % name)
                return 3
            if read(path) != text:
                print('CHECK FAILURE: %s on disk differs from the derivation' % name)
                return 3
            log('CHECK  %s  matches  sha256 %s' % (name, sha(text)))
        else:
            write(path, text)
            log('OUTPUT %s  sha256 %s  (%d bytes)'
                % (name, sha(text), len(text.encode('utf-8'))))
    return 0


if __name__ == '__main__':
    sys.exit(main())
